$axure.loadCurrentPage({
  "url":"新闻内容页.html",
  "generationDate":new Date(1417659391321.15),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7803f98d83f5436eaf1ed8e143fdcbef",
    "type":"Axure:Page",
    "name":"新闻内容页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e932359b93104bcbb33875ec4bb380db",
          "label":"背景",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":399,
              "height":745}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1e4e2ba941646b5a83574f85dd76476",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":399,
                  "height":745}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/中国大学生在线/背景_u0.png"}},
{
          "id":"aa3c1d1cbb0b4921bbb02af6bee0a35c",
          "label":"头部",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFEB1015},
            "location":{
              "x":35,
              "y":138},
            "size":{
              "width":319,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06ded7d279794288880004febada506d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEB1015},
                "location":{
                  "x":35,
                  "y":138},
                "size":{
                  "width":319,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页--未登录/头部_u2.png"}},
{
          "id":"529f283f06204f73a3e262527351052f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":38,
              "y":142},
            "size":{
              "width":13,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43be7b5618b647fc816675be0f231e3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":38,
                  "y":142},
                "size":{
                  "width":13,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页--未登录",
                      "target":{
                        "targetType":"page",
                        "url":"首页--未登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"104bdef7780949dfbda9ce404b3952b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":48,
              "y":175},
            "size":{
              "width":225,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57e89318c0c7451f81c5360a306eb677",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":48,
                  "y":175},
                "size":{
                  "width":225,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2c465d85bfe747149edede6a42cef577",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":48,
              "y":205},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67c891676e3c4531b79ecca85a397fbc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":48,
                  "y":205},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"80c14c3b08844696bec5404f185703d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "location":{
              "x":120,
              "y":203},
            "size":{
              "width":82,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8cd1cfffd2bf45939172b6f61d370e11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "location":{
                  "x":120,
                  "y":203},
                "size":{
                  "width":82,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"06a96982d7d34dff919920e189d3bd54",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":47,
              "y":228},
            "size":{
              "width":294,
              "height":336}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5734ee7680f341b58646fa867d8f4bbc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":47,
                  "y":228},
                "size":{
                  "width":294,
                  "height":336}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"00c0883c04c44d3597855d816a3f9299",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":47,
              "y":314},
            "size":{
              "width":294,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0cc61edd17014171a1e0931d9e03316b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":47,
                  "y":314},
                "size":{
                  "width":294,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新闻内容页/u14.png"}},
{
          "id":"e334962ae5bc4765820f091e249a4a0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEEECE1},
            "location":{
              "x":36,
              "y":568},
            "size":{
              "width":317,
              "height":26},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7f759d4f7fe47cdb35714afc21347ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEEECE1},
                "location":{
                  "x":36,
                  "y":568},
                "size":{
                  "width":317,
                  "height":26},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新闻内容页/u16.png"}},
{
          "id":"e22e790f0e0542d3bc2f2cdc578300e8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":563},
            "size":{
              "width":317,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页--未登录/u4_line.png"}},
{
          "id":"5438be6ac9554c8280c7a06527174ed8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":323,
              "y":571.5},
            "size":{
              "width":18,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e4923c977f44ffb8ec9ea99170f692a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":323,
                  "y":571.5},
                "size":{
                  "width":18,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 分享页面",
                      "objectsToFades":[{
                          "objectPath":["ba4a641ecb8146eab816e277d79376ed"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/新闻内容页/u19.png"}},
{
          "id":"7cbf2c73fa14452f87e51854f65bd7bc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":569},
            "size":{
              "width":122,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04a2eaf2519941d0a886d1ac069416ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":569},
                "size":{
                  "width":122,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新闻内容页/u21.png"}},
{
          "id":"3439e9bc67fe4ed68113c6012808abce",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":56,
              "y":571},
            "size":{
              "width":50,
              "height":18}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 写评论",
                      "target":{
                        "targetType":"page",
                        "url":"写评论.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"67125a69c9124354a05518fecc19fa8f",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":569},
            "size":{
              "width":40,
              "height":22}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 显示评论",
                      "target":{
                        "targetType":"page",
                        "url":"显示评论.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"ba4a641ecb8146eab816e277d79376ed",
          "label":"分享页面",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":36,
              "y":494},
            "size":{
              "width":317,
              "height":100},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5b11ea60ff54007b21c8be5b532e562",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":36,
                  "y":494},
                "size":{
                  "width":317,
                  "height":100},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 分享页面",
                      "objectsToFades":[{
                          "objectPath":["ba4a641ecb8146eab816e277d79376ed"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/新闻内容页/分享页面_u25.png"}},
{
          "id":"1f3d0613cc804e728df6331ef8f57263",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":438,
              "y":338},
            "size":{
              "width":52,
              "height":22},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63ec449b40114b5a9b29852970a256a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":438,
                  "y":338},
                "size":{
                  "width":52,
                  "height":22},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新闻内容页/u27.png"}},
{
          "id":"f6cb715ea19846d58305ea34d6c887d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":490,
              "y":338},
            "size":{
              "width":415,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd45b8a6343340709326a9f5ba6ec4d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":490,
                  "y":338},
                "size":{
                  "width":415,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "e932359b93104bcbb33875ec4bb380db":{
      "scriptId":"u0"},
    "e1e4e2ba941646b5a83574f85dd76476":{
      "scriptId":"u1"},
    "aa3c1d1cbb0b4921bbb02af6bee0a35c":{
      "scriptId":"u2"},
    "06ded7d279794288880004febada506d":{
      "scriptId":"u3"},
    "529f283f06204f73a3e262527351052f":{
      "scriptId":"u4"},
    "43be7b5618b647fc816675be0f231e3e":{
      "scriptId":"u5"},
    "104bdef7780949dfbda9ce404b3952b4":{
      "scriptId":"u6"},
    "57e89318c0c7451f81c5360a306eb677":{
      "scriptId":"u7"},
    "2c465d85bfe747149edede6a42cef577":{
      "scriptId":"u8"},
    "67c891676e3c4531b79ecca85a397fbc":{
      "scriptId":"u9"},
    "80c14c3b08844696bec5404f185703d3":{
      "scriptId":"u10"},
    "8cd1cfffd2bf45939172b6f61d370e11":{
      "scriptId":"u11"},
    "06a96982d7d34dff919920e189d3bd54":{
      "scriptId":"u12"},
    "5734ee7680f341b58646fa867d8f4bbc":{
      "scriptId":"u13"},
    "00c0883c04c44d3597855d816a3f9299":{
      "scriptId":"u14"},
    "0cc61edd17014171a1e0931d9e03316b":{
      "scriptId":"u15"},
    "e334962ae5bc4765820f091e249a4a0f":{
      "scriptId":"u16"},
    "f7f759d4f7fe47cdb35714afc21347ba":{
      "scriptId":"u17"},
    "e22e790f0e0542d3bc2f2cdc578300e8":{
      "scriptId":"u18"},
    "5438be6ac9554c8280c7a06527174ed8":{
      "scriptId":"u19"},
    "5e4923c977f44ffb8ec9ea99170f692a":{
      "scriptId":"u20"},
    "7cbf2c73fa14452f87e51854f65bd7bc":{
      "scriptId":"u21"},
    "04a2eaf2519941d0a886d1ac069416ab":{
      "scriptId":"u22"},
    "3439e9bc67fe4ed68113c6012808abce":{
      "scriptId":"u23"},
    "67125a69c9124354a05518fecc19fa8f":{
      "scriptId":"u24"},
    "ba4a641ecb8146eab816e277d79376ed":{
      "scriptId":"u25"},
    "b5b11ea60ff54007b21c8be5b532e562":{
      "scriptId":"u26"},
    "1f3d0613cc804e728df6331ef8f57263":{
      "scriptId":"u27"},
    "63ec449b40114b5a9b29852970a256a9":{
      "scriptId":"u28"},
    "f6cb715ea19846d58305ea34d6c887d6":{
      "scriptId":"u29"},
    "bd45b8a6343340709326a9f5ba6ec4d2":{
      "scriptId":"u30"}}});