$axure.loadCurrentPage({
  "url":"编辑个人信息页.html",
  "generationDate":new Date(1417659390583.11),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"eafa5389d3444417bb871c3c8e51c860",
    "type":"Axure:Page",
    "name":"编辑个人信息页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8620167f0a514f9b8671aacfca06bb63",
          "label":"背景",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":399,
              "height":745}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3fbc2b167894071a6442b1a154dc054",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":399,
                  "height":745}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/中国大学生在线/背景_u0.png"}},
{
          "id":"87d5557374e14d81a90b7f03a9430218",
          "label":"头部",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFEB1015},
            "location":{
              "x":35,
              "y":138},
            "size":{
              "width":319,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"164f2360ae4542278347a16f87c5bcf9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEB1015},
                "location":{
                  "x":35,
                  "y":138},
                "size":{
                  "width":319,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页--未登录/头部_u2.png"}},
{
          "id":"da0e0068a0ea4a98a7d1e45a6c1ba800",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":38,
              "y":142},
            "size":{
              "width":13,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"280c99764eee442bbb0250573c758d55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":38,
                  "y":142},
                "size":{
                  "width":13,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 全局页面--已登录",
                      "target":{
                        "targetType":"page",
                        "url":"全局页面--已登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4cff7a631e2f4a93bd30377f45558d34",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":119,
              "y":232},
            "size":{
              "width":114,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f0de9abc938453eb2c4a91f34eccf0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":119,
                  "y":232},
                "size":{
                  "width":114,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"58412ecc054c4917be98c86847230248",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":399,
              "y":140},
            "size":{
              "width":221,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76a43800d89a4f1c8804713a5d82888b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":399,
                  "y":140},
                "size":{
                  "width":221,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c833135a6b9e4238adccc4f87fe7ce13",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":119,
              "y":255},
            "size":{
              "width":114,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"134fc916d3ce4b49ba916b1e50b2b06b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":119,
                  "y":255},
                "size":{
                  "width":114,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"77b63561749d4fd78d5a9b2a8e46b1e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":107,
              "y":330},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"192384a412d7477193ddf1cb98196a30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":107,
                  "y":330},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ffb377ccbb2e45fc83859b6d50c5612a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":107,
              "y":290},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5955a688bbf44a5ca9fb905e211d6b60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":107,
                  "y":290},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"43e26dc1baab417e972a77790130b012",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":107,
              "y":203},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c27583b46ec4c62a88ab2593640acfd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":107,
                  "y":203},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0382406b955c4d35af42f93092db7d99",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":182},
            "size":{
              "width":50,
              "height":50},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"215223a0c75a462f82c013a83ada581e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":182},
                "size":{
                  "width":50,
                  "height":50},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑个人信息页/u18.png"}},
{
          "id":"3f357e0be8df486b896a09be268488d9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":107,
              "y":232},
            "size":{
              "width":200,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/编辑个人信息页/u20_line.png"}},
{
          "id":"4e46372eda9141fb8f60c5e2b9acb59f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":107,
              "y":310},
            "size":{
              "width":200,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/编辑个人信息页/u20_line.png"}},
{
          "id":"252d7b2806ee40ad80ae1f72148c9ec8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":107,
              "y":349},
            "size":{
              "width":200,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/编辑个人信息页/u20_line.png"}},
{
          "id":"cb401d79535842ad9670c8e98a29f0a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":220,
              "y":293},
            "size":{
              "width":42,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c3157ea933746e7b9fe3460206ee854",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":220,
                  "y":293},
                "size":{
                  "width":42,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a163f4010e24f9e862457a736feb559",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":236,
              "y":330},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31571bf1b9d54300b2e5017f6d2f3472",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":236,
                  "y":330},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2d15d31306e04957a32b757b03a24008",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":106,
              "y":253},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ee90c562ac24f5b8a60de10bc890aac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":106,
                  "y":253},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc40fee1b9174667a66dd973ea967afe",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":106,
              "y":273},
            "size":{
              "width":200,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/编辑个人信息页/u20_line.png"}},
{
          "id":"684509f382784187aded2c551a3b3b8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":219,
              "y":256},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93677884c5834c90a3c2f54455cf6e65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":219,
                  "y":256},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8c81ac1db81e42cf95c46380630446f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":399,
              "y":188},
            "size":{
              "width":310,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7995e21a59f4044bd1d5d4dada5459f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":399,
                  "y":188},
                "size":{
                  "width":310,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1378751d5992492eac355c270cec16a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":415,
              "y":324},
            "size":{
              "width":123,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dae68ccfa5824aa7838e1382b24c2dea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":415,
                  "y":324},
                "size":{
                  "width":123,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f113cacd90ff46418742d31290f7ae59",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":288,
              "y":141},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 全局页面--已登录",
                      "target":{
                        "targetType":"page",
                        "url":"全局页面--已登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"a144871af3f44973a55c3681912ede70",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":56,
              "y":143},
            "size":{
              "width":65,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17c33986516c4c9190de8d6961a41a0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":56,
                  "y":143},
                "size":{
                  "width":65,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"21ac29c96d9f4350839b1e78ca50597b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":399,
              "y":232},
            "size":{
              "width":263,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"983d28edf7f44c46aa31590237075d06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":399,
                  "y":232},
                "size":{
                  "width":263,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "8620167f0a514f9b8671aacfca06bb63":{
      "scriptId":"u0"},
    "d3fbc2b167894071a6442b1a154dc054":{
      "scriptId":"u1"},
    "87d5557374e14d81a90b7f03a9430218":{
      "scriptId":"u2"},
    "164f2360ae4542278347a16f87c5bcf9":{
      "scriptId":"u3"},
    "da0e0068a0ea4a98a7d1e45a6c1ba800":{
      "scriptId":"u4"},
    "280c99764eee442bbb0250573c758d55":{
      "scriptId":"u5"},
    "4cff7a631e2f4a93bd30377f45558d34":{
      "scriptId":"u6"},
    "5f0de9abc938453eb2c4a91f34eccf0b":{
      "scriptId":"u7"},
    "58412ecc054c4917be98c86847230248":{
      "scriptId":"u8"},
    "76a43800d89a4f1c8804713a5d82888b":{
      "scriptId":"u9"},
    "c833135a6b9e4238adccc4f87fe7ce13":{
      "scriptId":"u10"},
    "134fc916d3ce4b49ba916b1e50b2b06b":{
      "scriptId":"u11"},
    "77b63561749d4fd78d5a9b2a8e46b1e4":{
      "scriptId":"u12"},
    "192384a412d7477193ddf1cb98196a30":{
      "scriptId":"u13"},
    "ffb377ccbb2e45fc83859b6d50c5612a":{
      "scriptId":"u14"},
    "5955a688bbf44a5ca9fb905e211d6b60":{
      "scriptId":"u15"},
    "43e26dc1baab417e972a77790130b012":{
      "scriptId":"u16"},
    "4c27583b46ec4c62a88ab2593640acfd":{
      "scriptId":"u17"},
    "0382406b955c4d35af42f93092db7d99":{
      "scriptId":"u18"},
    "215223a0c75a462f82c013a83ada581e":{
      "scriptId":"u19"},
    "3f357e0be8df486b896a09be268488d9":{
      "scriptId":"u20"},
    "4e46372eda9141fb8f60c5e2b9acb59f":{
      "scriptId":"u21"},
    "252d7b2806ee40ad80ae1f72148c9ec8":{
      "scriptId":"u22"},
    "cb401d79535842ad9670c8e98a29f0a3":{
      "scriptId":"u23"},
    "8c3157ea933746e7b9fe3460206ee854":{
      "scriptId":"u24"},
    "4a163f4010e24f9e862457a736feb559":{
      "scriptId":"u25"},
    "31571bf1b9d54300b2e5017f6d2f3472":{
      "scriptId":"u26"},
    "2d15d31306e04957a32b757b03a24008":{
      "scriptId":"u27"},
    "8ee90c562ac24f5b8a60de10bc890aac":{
      "scriptId":"u28"},
    "fc40fee1b9174667a66dd973ea967afe":{
      "scriptId":"u29"},
    "684509f382784187aded2c551a3b3b8d":{
      "scriptId":"u30"},
    "93677884c5834c90a3c2f54455cf6e65":{
      "scriptId":"u31"},
    "8c81ac1db81e42cf95c46380630446f0":{
      "scriptId":"u32"},
    "a7995e21a59f4044bd1d5d4dada5459f":{
      "scriptId":"u33"},
    "1378751d5992492eac355c270cec16a1":{
      "scriptId":"u34"},
    "dae68ccfa5824aa7838e1382b24c2dea":{
      "scriptId":"u35"},
    "f113cacd90ff46418742d31290f7ae59":{
      "scriptId":"u36"},
    "a144871af3f44973a55c3681912ede70":{
      "scriptId":"u37"},
    "17c33986516c4c9190de8d6961a41a0b":{
      "scriptId":"u38"},
    "21ac29c96d9f4350839b1e78ca50597b":{
      "scriptId":"u39"},
    "983d28edf7f44c46aa31590237075d06":{
      "scriptId":"u40"}}});