$axure.loadCurrentPage({
  "url":"显示评论.html",
  "generationDate":new Date(1417659391450.16),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"986d33f72a9b4317b211ac6b20724a2e",
    "type":"Axure:Page",
    "name":"显示评论",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e932359b93104bcbb33875ec4bb380db",
          "label":"背景",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":399,
              "height":745}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1e4e2ba941646b5a83574f85dd76476",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":399,
                  "height":745}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/中国大学生在线/背景_u0.png"}},
{
          "id":"aa3c1d1cbb0b4921bbb02af6bee0a35c",
          "label":"头部",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFEB1015},
            "location":{
              "x":35,
              "y":138},
            "size":{
              "width":319,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06ded7d279794288880004febada506d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEB1015},
                "location":{
                  "x":35,
                  "y":138},
                "size":{
                  "width":319,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页--未登录/头部_u2.png"}},
{
          "id":"529f283f06204f73a3e262527351052f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":38,
              "y":142},
            "size":{
              "width":13,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43be7b5618b647fc816675be0f231e3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":38,
                  "y":142},
                "size":{
                  "width":13,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页--未登录",
                      "target":{
                        "targetType":"page",
                        "url":"首页--未登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e334962ae5bc4765820f091e249a4a0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEEECE1},
            "location":{
              "x":36,
              "y":568},
            "size":{
              "width":317,
              "height":26},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7f759d4f7fe47cdb35714afc21347ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEEECE1},
                "location":{
                  "x":36,
                  "y":568},
                "size":{
                  "width":317,
                  "height":26},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新闻内容页/u16.png"}},
{
          "id":"e22e790f0e0542d3bc2f2cdc578300e8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":563},
            "size":{
              "width":317,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页--未登录/u4_line.png"}},
{
          "id":"5438be6ac9554c8280c7a06527174ed8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":323,
              "y":571.5},
            "size":{
              "width":18,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e4923c977f44ffb8ec9ea99170f692a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":323,
                  "y":571.5},
                "size":{
                  "width":18,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 分享页面",
                      "objectsToFades":[{
                          "objectPath":["754ac7d2330a4982ab519f364cc8d80c"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/新闻内容页/u19.png"}},
{
          "id":"816dd903f41b4caa864b8b50f8b771ae",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":569},
            "size":{
              "width":122,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"522b864b98034bb38e490f7c559f2538",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":569},
                "size":{
                  "width":122,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新闻内容页/u21.png"}},
{
          "id":"febb238e0ada43219613acce5e3a5bdd",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":56,
              "y":571},
            "size":{
              "width":50,
              "height":18}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 写评论",
                      "target":{
                        "targetType":"page",
                        "url":"写评论.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"6b0c63bebc914b61bb20e7f1c961f534",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":569},
            "size":{
              "width":40,
              "height":22}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 显示评论",
                      "target":{
                        "targetType":"page",
                        "url":"显示评论.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"754ac7d2330a4982ab519f364cc8d80c",
          "label":"分享页面",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":36,
              "y":550},
            "size":{
              "width":317,
              "height":44},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2d01c70e02f45b1b52bc4877bbb56c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":36,
                  "y":550},
                "size":{
                  "width":317,
                  "height":44},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 分享页面",
                      "objectsToFades":[{
                          "objectPath":["754ac7d2330a4982ab519f364cc8d80c"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/显示评论/分享页面_u15.png"}},
{
          "id":"da6b67503b214b83b894c300357fb926",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":35,
              "y":169},
            "size":{
              "width":318,
              "height":68}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ebbc7f982c2640eba705bce101b81266",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":35,
                  "y":169},
                "size":{
                  "width":318,
                  "height":68}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/显示评论/u17.png"}},
{
          "id":"a11c519152fd471494f2cd8629177de2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":297},
            "size":{
              "width":8,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b25f76a3ec5d427aae5f5d6e14086dff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":297},
                "size":{
                  "width":8,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a547e9b80d1c40e9bec54dbabf851317",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":396,
              "y":288.5},
            "size":{
              "width":32,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"700940afdb7342338f8425da787c8ccb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":396,
                  "y":288.5},
                "size":{
                  "width":32,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/显示评论/u21.png"}},
{
          "id":"7f8bc0bdf26842b68886c10702dca189",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":438,
              "y":296},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a48c70c9ab644792a8162945cecc0c03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":438,
                  "y":296},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5fba0808142a430684e9d23b82782c96",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":396,
              "y":184},
            "size":{
              "width":177,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2473f8a19b6413597be0cfad3f95221",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":396,
                  "y":184},
                "size":{
                  "width":177,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f5be112e3fd342099cc3a4c83bc63371",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":396,
              "y":374},
            "size":{
              "width":129,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba11cd1accea41768cf88d20cd433ec5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":396,
                  "y":374},
                "size":{
                  "width":129,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"78103186d50f4f20ae5c9968919e424b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":550,
              "y":363.5},
            "size":{
              "width":120,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"354d7df4d1ed43528c008f5c67fd6067",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":550,
                  "y":363.5},
                "size":{
                  "width":120,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/显示评论/u29.png"}},
{
          "id":"eb4528348327442db70ae2ffd3fa866c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":568,
              "y":376},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8608437506c458393cbb1661a55caab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":568,
                  "y":376},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/显示评论/u31.png"}},
{
          "id":"311e1facdf0c4aaeb4d6b728f5804c03",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":622,
              "y":376},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f80746815e9349828e6dbe2b9068a655",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":622,
                  "y":376},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/显示评论/u31.png"}},
{
          "id":"29a6a5448943403dbcbce6e9235f264c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":690,
              "y":376},
            "size":{
              "width":193,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f368da07617a4dc2b2eec4897bc7665d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":690,
                  "y":376},
                "size":{
                  "width":193,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6ee772b9cccc4fefb5de356c61ab8aa6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":35,
              "y":236},
            "size":{
              "width":318,
              "height":317}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2df59a0c8f7945d9b5f97a92e26fbc7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":35,
                  "y":236},
                "size":{
                  "width":318,
                  "height":317}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/显示评论/u37.png"}},
{
          "id":"b4a9c5a14eff47a59b6c6ee5afbb07c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":39,
              "y":251},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a11529b6e8849b8b5d1fbea5d28b38a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":39,
                  "y":251},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eeba75fa1ff748569402ee3d50ac4857",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":39,
              "y":361},
            "size":{
              "width":24,
              "height":24},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"acde9f1c180f424e9e3718705a1fa0cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":39,
                  "y":361},
                "size":{
                  "width":24,
                  "height":24},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/显示评论/u41.png"}},
{
          "id":"e34b5da2d1054cfb8af857ed8a350113",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0066FF,
              "opacity":1},
            "location":{
              "x":73,
              "y":367},
            "size":{
              "width":93,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f5bafeb298441849081a45e726b87ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF,
                  "opacity":1},
                "location":{
                  "x":73,
                  "y":367},
                "size":{
                  "width":93,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"72c441ff591447a99c737955b0eecf3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":73,
              "y":387},
            "size":{
              "width":44,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e803645dc634b0b8b4fbddd31440bf6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":73,
                  "y":387},
                "size":{
                  "width":44,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f84db80d52b746e896a516f035d0cdbe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":73,
              "y":410},
            "size":{
              "width":265,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"915bea16c9d845abb6dc3aec6657e948",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":73,
                  "y":410},
                "size":{
                  "width":265,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"024e1324fc724ff888363c97f3f45121",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":73,
              "y":288},
            "size":{
              "width":149,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26382cb86ed94fae928393af802d7b09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":73,
                  "y":288},
                "size":{
                  "width":149,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c55141ff39fa458fa704717ba90f4799",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":73,
              "y":310},
            "size":{
              "width":51,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2fe3568057ca4e31b3737286afbd563a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":73,
                  "y":310},
                "size":{
                  "width":51,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"89c4208ad88d4746970e3218ada7297f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":73,
              "y":333},
            "size":{
              "width":196,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df6a738e16f5483eb5c614a801461b88",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":73,
                  "y":333},
                "size":{
                  "width":196,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"675f6a98beab41939b43b53d20f3a6ec",
          "label":"image map",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":35,
              "y":360},
            "size":{
              "width":318,
              "height":153}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 (动态面板) 淡入淡出 500 ms",
                      "objectsToFades":[{
                          "objectPath":["c57db88caefc4dc6b04529f3581185bd"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"fade",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"1d1ffb70c88c481c9149e92e67783bed",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":39,
              "y":283},
            "size":{
              "width":24,
              "height":24},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f852d42d3e4a48d59d0678098955fd70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":39,
                  "y":283},
                "size":{
                  "width":24,
                  "height":24},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/显示评论/u41.png"}},
{
          "id":"48c291fd0fe44d098a8c1f5d28e63f32",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":287,
              "y":246},
            "size":{
              "width":32,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30aab13273554e0f8cf757563e965691",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":287,
                  "y":246},
                "size":{
                  "width":32,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/显示评论/u21.png"}},
{
          "id":"78e299f2a09e40348573b93945d67f3d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":319,
              "y":257},
            "size":{
              "width":22,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1081ed4281648349d003cc23053d97c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":319,
                  "y":257},
                "size":{
                  "width":22,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c57db88caefc4dc6b04529f3581185bd",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":120,
              "y":449},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"741aec4b17294cfca179d10329236de1",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"1c97cbd946d9401f9216e780089920cb",
                  "label":"",
                  "parentDynamicPanel":"c57db88caefc4dc6b04529f3581185bd",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF333333},
                    "size":{
                      "width":120,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"187025d6e5e94cf0a33e4d02de3c64d7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c57db88caefc4dc6b04529f3581185bd",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF333333},
                        "size":{
                          "width":120,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/显示评论/u29.png"}},
{
                  "id":"f9d0fbe7e3614ba9a35157ef4eeb59ce",
                  "label":"",
                  "parentDynamicPanel":"c57db88caefc4dc6b04529f3581185bd",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF333333},
                    "location":{
                      "x":18,
                      "y":12},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6babe949756a4d9386807eadb256a236",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c57db88caefc4dc6b04529f3581185bd",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF333333},
                        "location":{
                          "x":18,
                          "y":12},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/显示评论/u31.png"}},
{
                  "id":"c315faf148c0432591bdc20e3e570c17",
                  "label":"",
                  "parentDynamicPanel":"c57db88caefc4dc6b04529f3581185bd",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF333333},
                    "location":{
                      "x":72,
                      "y":12},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1c1c6a470e364ccda00f531b51a9e740",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c57db88caefc4dc6b04529f3581185bd",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF333333},
                        "location":{
                          "x":72,
                          "y":12},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/显示评论/u31.png"}},
{
                  "id":"a2bb2607ae704469bb23996695bf5d83",
                  "label":"image map",
                  "parentDynamicPanel":"c57db88caefc4dc6b04529f3581185bd",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":60,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 回复评论",
                              "target":{
                                "targetType":"page",
                                "url":"回复评论.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true}]}]},
{
          "id":"7813713041554d1d8393c2ee48583baa",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":39,
              "y":272},
            "size":{
              "width":299,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/显示评论/u70_line.png"}},
{
          "id":"d4d64d462087409fa29f54f223575c7e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":39,
              "y":513},
            "size":{
              "width":299,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/显示评论/u70_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "e932359b93104bcbb33875ec4bb380db":{
      "scriptId":"u0"},
    "e1e4e2ba941646b5a83574f85dd76476":{
      "scriptId":"u1"},
    "aa3c1d1cbb0b4921bbb02af6bee0a35c":{
      "scriptId":"u2"},
    "06ded7d279794288880004febada506d":{
      "scriptId":"u3"},
    "529f283f06204f73a3e262527351052f":{
      "scriptId":"u4"},
    "43be7b5618b647fc816675be0f231e3e":{
      "scriptId":"u5"},
    "e334962ae5bc4765820f091e249a4a0f":{
      "scriptId":"u6"},
    "f7f759d4f7fe47cdb35714afc21347ba":{
      "scriptId":"u7"},
    "e22e790f0e0542d3bc2f2cdc578300e8":{
      "scriptId":"u8"},
    "5438be6ac9554c8280c7a06527174ed8":{
      "scriptId":"u9"},
    "5e4923c977f44ffb8ec9ea99170f692a":{
      "scriptId":"u10"},
    "816dd903f41b4caa864b8b50f8b771ae":{
      "scriptId":"u11"},
    "522b864b98034bb38e490f7c559f2538":{
      "scriptId":"u12"},
    "febb238e0ada43219613acce5e3a5bdd":{
      "scriptId":"u13"},
    "6b0c63bebc914b61bb20e7f1c961f534":{
      "scriptId":"u14"},
    "754ac7d2330a4982ab519f364cc8d80c":{
      "scriptId":"u15"},
    "c2d01c70e02f45b1b52bc4877bbb56c5":{
      "scriptId":"u16"},
    "da6b67503b214b83b894c300357fb926":{
      "scriptId":"u17"},
    "ebbc7f982c2640eba705bce101b81266":{
      "scriptId":"u18"},
    "a11c519152fd471494f2cd8629177de2":{
      "scriptId":"u19"},
    "b25f76a3ec5d427aae5f5d6e14086dff":{
      "scriptId":"u20"},
    "a547e9b80d1c40e9bec54dbabf851317":{
      "scriptId":"u21"},
    "700940afdb7342338f8425da787c8ccb":{
      "scriptId":"u22"},
    "7f8bc0bdf26842b68886c10702dca189":{
      "scriptId":"u23"},
    "a48c70c9ab644792a8162945cecc0c03":{
      "scriptId":"u24"},
    "5fba0808142a430684e9d23b82782c96":{
      "scriptId":"u25"},
    "e2473f8a19b6413597be0cfad3f95221":{
      "scriptId":"u26"},
    "f5be112e3fd342099cc3a4c83bc63371":{
      "scriptId":"u27"},
    "ba11cd1accea41768cf88d20cd433ec5":{
      "scriptId":"u28"},
    "78103186d50f4f20ae5c9968919e424b":{
      "scriptId":"u29"},
    "354d7df4d1ed43528c008f5c67fd6067":{
      "scriptId":"u30"},
    "eb4528348327442db70ae2ffd3fa866c":{
      "scriptId":"u31"},
    "c8608437506c458393cbb1661a55caab":{
      "scriptId":"u32"},
    "311e1facdf0c4aaeb4d6b728f5804c03":{
      "scriptId":"u33"},
    "f80746815e9349828e6dbe2b9068a655":{
      "scriptId":"u34"},
    "29a6a5448943403dbcbce6e9235f264c":{
      "scriptId":"u35"},
    "f368da07617a4dc2b2eec4897bc7665d":{
      "scriptId":"u36"},
    "6ee772b9cccc4fefb5de356c61ab8aa6":{
      "scriptId":"u37"},
    "2df59a0c8f7945d9b5f97a92e26fbc7f":{
      "scriptId":"u38"},
    "b4a9c5a14eff47a59b6c6ee5afbb07c9":{
      "scriptId":"u39"},
    "9a11529b6e8849b8b5d1fbea5d28b38a":{
      "scriptId":"u40"},
    "eeba75fa1ff748569402ee3d50ac4857":{
      "scriptId":"u41"},
    "acde9f1c180f424e9e3718705a1fa0cc":{
      "scriptId":"u42"},
    "e34b5da2d1054cfb8af857ed8a350113":{
      "scriptId":"u43"},
    "3f5bafeb298441849081a45e726b87ec":{
      "scriptId":"u44"},
    "72c441ff591447a99c737955b0eecf3e":{
      "scriptId":"u45"},
    "0e803645dc634b0b8b4fbddd31440bf6":{
      "scriptId":"u46"},
    "f84db80d52b746e896a516f035d0cdbe":{
      "scriptId":"u47"},
    "915bea16c9d845abb6dc3aec6657e948":{
      "scriptId":"u48"},
    "024e1324fc724ff888363c97f3f45121":{
      "scriptId":"u49"},
    "26382cb86ed94fae928393af802d7b09":{
      "scriptId":"u50"},
    "c55141ff39fa458fa704717ba90f4799":{
      "scriptId":"u51"},
    "2fe3568057ca4e31b3737286afbd563a":{
      "scriptId":"u52"},
    "89c4208ad88d4746970e3218ada7297f":{
      "scriptId":"u53"},
    "df6a738e16f5483eb5c614a801461b88":{
      "scriptId":"u54"},
    "675f6a98beab41939b43b53d20f3a6ec":{
      "scriptId":"u55"},
    "1d1ffb70c88c481c9149e92e67783bed":{
      "scriptId":"u56"},
    "f852d42d3e4a48d59d0678098955fd70":{
      "scriptId":"u57"},
    "48c291fd0fe44d098a8c1f5d28e63f32":{
      "scriptId":"u58"},
    "30aab13273554e0f8cf757563e965691":{
      "scriptId":"u59"},
    "78e299f2a09e40348573b93945d67f3d":{
      "scriptId":"u60"},
    "c1081ed4281648349d003cc23053d97c":{
      "scriptId":"u61"},
    "c57db88caefc4dc6b04529f3581185bd":{
      "scriptId":"u62"},
    "1c97cbd946d9401f9216e780089920cb":{
      "scriptId":"u63"},
    "187025d6e5e94cf0a33e4d02de3c64d7":{
      "scriptId":"u64"},
    "f9d0fbe7e3614ba9a35157ef4eeb59ce":{
      "scriptId":"u65"},
    "6babe949756a4d9386807eadb256a236":{
      "scriptId":"u66"},
    "c315faf148c0432591bdc20e3e570c17":{
      "scriptId":"u67"},
    "1c1c6a470e364ccda00f531b51a9e740":{
      "scriptId":"u68"},
    "a2bb2607ae704469bb23996695bf5d83":{
      "scriptId":"u69"},
    "7813713041554d1d8393c2ee48583baa":{
      "scriptId":"u70"},
    "d4d64d462087409fa29f54f223575c7e":{
      "scriptId":"u71"}}});