$axure.loadCurrentPage({
  "url":"首页--登录.html",
  "generationDate":new Date(1417659391192.14),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b4881bbfcc8340b0802ea237d39b7017",
    "type":"Axure:Page",
    "name":"首页--登录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e932359b93104bcbb33875ec4bb380db",
          "label":"背景",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":399,
              "height":745}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1e4e2ba941646b5a83574f85dd76476",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":399,
                  "height":745}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/中国大学生在线/背景_u0.png"}},
{
          "id":"aa3c1d1cbb0b4921bbb02af6bee0a35c",
          "label":"头部",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFEB1015},
            "location":{
              "x":35,
              "y":138},
            "size":{
              "width":319,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06ded7d279794288880004febada506d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEB1015},
                "location":{
                  "x":35,
                  "y":138},
                "size":{
                  "width":319,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页--未登录/头部_u2.png"}},
{
          "id":"ab770a0b8d3b4439b042fb3760432b2f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":193},
            "size":{
              "width":317,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页--未登录/u4_line.png"}},
{
          "id":"e7743b49cc0f45e4b84d280459424e7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFEB1015},
            "location":{
              "x":76,
              "y":173},
            "size":{
              "width":40,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b3a7b747802491e91e575010a8328f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEB1015},
                "location":{
                  "x":76,
                  "y":173},
                "size":{
                  "width":40,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页--未登录/u5.png"}},
{
          "id":"764111022b11419489a141bfbf8e395b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":135,
              "y":175},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13dad9b2ac25400b88b096ddd1aefc7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":135,
                  "y":175},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"82ad2dcbd911477e8905e6f3dae7e2f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":181,
              "y":175},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80064c1872174a3f91b7debe4d8e5a69",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":181,
                  "y":175},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4fd1b8c760154b7b9309ec9fe1452634",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":228,
              "y":175},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8dd25cf8eb93413a8b87a641b976c8b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":228,
                  "y":175},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c1062ccbb074d0b9804dad55800e4ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":274,
              "y":175},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"269f31a80500432e9a7b6a3594c1b8ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":274,
                  "y":175},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ee364468c6a41348115ca9632c56c9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":327,
              "y":171},
            "size":{
              "width":13,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3cbf1886d9a6477a87c89b189cc55a56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":327,
                  "y":171},
                "size":{
                  "width":13,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 标签选择页面",
                      "target":{
                        "targetType":"page",
                        "url":"标签选择页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"34ae75ef45fc4152830dc35805f64147",
          "label":"轮播图",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":202},
            "size":{
              "width":317,
              "height":80}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"3598abe0018644f59ef5cbf524de3742",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"277e8a4f9b224da9b8ae843687c94a04",
                  "label":"幻灯1",
                  "parentDynamicPanel":"34ae75ef45fc4152830dc35805f64147",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":317,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b39863ab5755487d8f164ea5c589848f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"34ae75ef45fc4152830dc35805f64147",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":317,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"moveWidget",
                              "description":"移动 幻灯1 相对位置为 (-317,0) 线性 500ms,<br>幻灯2 相对位置为 (-317,0) 线性 500ms,<br>幻灯3 相对位置为 (-317,0) 线性 500ms",
                              "objectsToMoves":[{
                                  "objectPath":["277e8a4f9b224da9b8ae843687c94a04"],
                                  "moveInfo":{
                                    "moveType":"delta",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"-317",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "options":{
                                      "easing":"linear",
                                      "duration":500}}},
{
                                  "objectPath":["81d588fcdcd8485ca45eb6b3c1cf0129"],
                                  "moveInfo":{
                                    "moveType":"delta",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"-317",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "options":{
                                      "easing":"linear",
                                      "duration":500}}},
{
                                  "objectPath":["e86c4d0f8a2c41e99d767fb9fe3824f2"],
                                  "moveInfo":{
                                    "moveType":"delta",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"-317",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "options":{
                                      "easing":"linear",
                                      "duration":500}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/首页--未登录/幻灯1_u18.jpg"}},
{
                  "id":"81d588fcdcd8485ca45eb6b3c1cf0129",
                  "label":"幻灯2",
                  "parentDynamicPanel":"34ae75ef45fc4152830dc35805f64147",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":317,
                      "y":0},
                    "size":{
                      "width":317,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b613bccbf67f427fa978b71873d9aeee",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"34ae75ef45fc4152830dc35805f64147",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":317,
                          "y":0},
                        "size":{
                          "width":317,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"moveWidget",
                              "description":"移动 幻灯2 相对位置为 (-317,0) 线性 500ms,<br>幻灯3 相对位置为 (-317,0) 线性 500ms",
                              "objectsToMoves":[{
                                  "objectPath":["81d588fcdcd8485ca45eb6b3c1cf0129"],
                                  "moveInfo":{
                                    "moveType":"delta",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"-317",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "options":{
                                      "easing":"linear",
                                      "duration":500}}},
{
                                  "objectPath":["e86c4d0f8a2c41e99d767fb9fe3824f2"],
                                  "moveInfo":{
                                    "moveType":"delta",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"-317",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "options":{
                                      "easing":"linear",
                                      "duration":500}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/首页--未登录/幻灯2_u20.jpg"}},
{
                  "id":"e86c4d0f8a2c41e99d767fb9fe3824f2",
                  "label":"幻灯3",
                  "parentDynamicPanel":"34ae75ef45fc4152830dc35805f64147",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":634,
                      "y":0},
                    "size":{
                      "width":317,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"99374ef73987474292b3137b9cae9ba0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"34ae75ef45fc4152830dc35805f64147",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":634,
                          "y":0},
                        "size":{
                          "width":317,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 新闻内容页",
                              "target":{
                                "targetType":"page",
                                "url":"新闻内容页.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/首页--未登录/幻灯3_u22.jpg"}}]}]},
{
          "id":"b215b01097a1415e9e5597955b2dd5b2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":279},
            "size":{
              "width":317,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页--未登录/u4_line.png"}},
{
          "id":"f47b66e63d93491796084d83a94971fb",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":365},
            "size":{
              "width":317,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页--未登录/u4_line.png"}},
{
          "id":"28b47998011048ef95d56ba3aa254f59",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":448},
            "size":{
              "width":317,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页--未登录/u4_line.png"}},
{
          "id":"405a88da932040ea9e222c7fb7bf0519",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":534},
            "size":{
              "width":317,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页--未登录/u4_line.png"}},
{
          "id":"41d1c2740700424bbfbe5f1e4d1eb6b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":134,
              "y":291},
            "size":{
              "width":222,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3b16f2fbd2a49418382d78ee4bf184b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":134,
                  "y":291},
                "size":{
                  "width":222,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 新闻内容页",
                      "target":{
                        "targetType":"page",
                        "url":"新闻内容页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"79f3ab3c5b9845ae86e92f37bd193158",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":290},
            "size":{
              "width":75,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20ca457487ab441982964212e1fa4690",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":290},
                "size":{
                  "width":75,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 新闻内容页",
                      "target":{
                        "targetType":"page",
                        "url":"新闻内容页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页--未登录/u30.jpg"}},
{
          "id":"116e7c417b834910b6d927c797c1223d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":135,
              "y":379},
            "size":{
              "width":222,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ea46bc69c55446babf623d05a3daf6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":135,
                  "y":379},
                "size":{
                  "width":222,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 组图内容页",
                      "target":{
                        "targetType":"page",
                        "url":"组图内容页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bc3ebb3a71a642baa9df5cccb78b8f20",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":51,
              "y":380},
            "size":{
              "width":75,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3fc2ad06cb4f417ba3589b9355260d0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":51,
                  "y":380},
                "size":{
                  "width":75,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 组图内容页",
                      "target":{
                        "targetType":"page",
                        "url":"组图内容页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页--未登录/u34.jpg"}},
{
          "id":"ea1d9a5e7feb4f418be0090bbd89b300",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":133,
              "y":464},
            "size":{
              "width":222,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2d349aa529341858b9b1b6fb07cf9dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":133,
                  "y":464},
                "size":{
                  "width":222,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 专题列表页",
                      "target":{
                        "targetType":"page",
                        "url":"专题列表页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4e4add97c14e400ca21590c209225fe8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":51,
              "y":464},
            "size":{
              "width":75,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e154668414d4031bb77bc642965388a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":51,
                  "y":464},
                "size":{
                  "width":75,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 专题列表页",
                      "target":{
                        "targetType":"page",
                        "url":"专题列表页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页--未登录/u38.jpg"}},
{
          "id":"0deac709d0c14befa28c2b5d4f63ce6e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":51,
              "y":354},
            "size":{
              "width":23,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53eb3afa12074e219e929470163410a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":51,
                  "y":354},
                "size":{
                  "width":23,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e764082176654a30b8f88cf00f1263d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":293,
              "y":354},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0619b339c28142408f3a66061919da0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":293,
                  "y":354},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d2b5284e56a842de88d4e7d718e1faaa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":51,
              "y":435},
            "size":{
              "width":23,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad573e6852084684b60cf30fb66c045e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":51,
                  "y":435},
                "size":{
                  "width":23,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"65a5fd0fc4874ec4b07c65ee440c39e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":287,
              "y":435},
            "size":{
              "width":46,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73835c35b53e4aceb37f40605e11bc3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":287,
                  "y":435},
                "size":{
                  "width":46,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"34bc9a24b5d241d8ac376d2c0fc33e56",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":51,
              "y":521},
            "size":{
              "width":23,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8965a7d904d04f9784568c7151d05874",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":51,
                  "y":521},
                "size":{
                  "width":23,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c54863f5d85c4fb7855e55225a7cf9b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":293,
              "y":521},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a08c91ba6631417fac99eea92b65bfec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":293,
                  "y":521},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8baac80b9ce4484cb891eec842c1d577",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"11px",
            "location":{
              "x":135,
              "y":316},
            "size":{
              "width":212,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04783517b4a04a8d8983ef192f6de932",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"11px",
                "location":{
                  "x":135,
                  "y":316},
                "size":{
                  "width":212,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 新闻内容页",
                      "target":{
                        "targetType":"page",
                        "url":"新闻内容页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9b73841f46084476b1dc36e1ff8c5ad6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"11px",
            "location":{
              "x":135,
              "y":400},
            "size":{
              "width":212,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8411b09345a9489cb2248dd40adef1fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"11px",
                "location":{
                  "x":135,
                  "y":400},
                "size":{
                  "width":212,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 组图内容页",
                      "target":{
                        "targetType":"page",
                        "url":"组图内容页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4316d48218a04bb18bcfb557621334d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"11px",
            "location":{
              "x":133,
              "y":485},
            "size":{
              "width":212,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46d71cc3fb0442f99985cc198fecf042",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"11px",
                "location":{
                  "x":133,
                  "y":485},
                "size":{
                  "width":212,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 专题列表页",
                      "target":{
                        "targetType":"page",
                        "url":"专题列表页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3ccbcdeae870410994448955f6c474d4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":323.5,
              "y":141},
            "size":{
              "width":20,
              "height":20},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c8896a6d744414ead0340fe1cf6d430",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":323.5,
                  "y":141},
                "size":{
                  "width":20,
                  "height":20},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 全局页面--已登录",
                      "target":{
                        "targetType":"page",
                        "url":"全局页面--已登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页--登录/u58.png"}},
{
          "id":"e686811e4a46401a936ef017d1810033",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":243,
              "y":354},
            "size":{
              "width":35,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed2c3451a41545bd91d2462dd95fddfb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":243,
                  "y":354},
                "size":{
                  "width":35,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "e932359b93104bcbb33875ec4bb380db":{
      "scriptId":"u0"},
    "e1e4e2ba941646b5a83574f85dd76476":{
      "scriptId":"u1"},
    "aa3c1d1cbb0b4921bbb02af6bee0a35c":{
      "scriptId":"u2"},
    "06ded7d279794288880004febada506d":{
      "scriptId":"u3"},
    "ab770a0b8d3b4439b042fb3760432b2f":{
      "scriptId":"u4"},
    "e7743b49cc0f45e4b84d280459424e7e":{
      "scriptId":"u5"},
    "1b3a7b747802491e91e575010a8328f4":{
      "scriptId":"u6"},
    "764111022b11419489a141bfbf8e395b":{
      "scriptId":"u7"},
    "13dad9b2ac25400b88b096ddd1aefc7e":{
      "scriptId":"u8"},
    "82ad2dcbd911477e8905e6f3dae7e2f1":{
      "scriptId":"u9"},
    "80064c1872174a3f91b7debe4d8e5a69":{
      "scriptId":"u10"},
    "4fd1b8c760154b7b9309ec9fe1452634":{
      "scriptId":"u11"},
    "8dd25cf8eb93413a8b87a641b976c8b7":{
      "scriptId":"u12"},
    "1c1062ccbb074d0b9804dad55800e4ed":{
      "scriptId":"u13"},
    "269f31a80500432e9a7b6a3594c1b8ea":{
      "scriptId":"u14"},
    "8ee364468c6a41348115ca9632c56c9c":{
      "scriptId":"u15"},
    "3cbf1886d9a6477a87c89b189cc55a56":{
      "scriptId":"u16"},
    "34ae75ef45fc4152830dc35805f64147":{
      "scriptId":"u17"},
    "277e8a4f9b224da9b8ae843687c94a04":{
      "scriptId":"u18"},
    "b39863ab5755487d8f164ea5c589848f":{
      "scriptId":"u19"},
    "81d588fcdcd8485ca45eb6b3c1cf0129":{
      "scriptId":"u20"},
    "b613bccbf67f427fa978b71873d9aeee":{
      "scriptId":"u21"},
    "e86c4d0f8a2c41e99d767fb9fe3824f2":{
      "scriptId":"u22"},
    "99374ef73987474292b3137b9cae9ba0":{
      "scriptId":"u23"},
    "b215b01097a1415e9e5597955b2dd5b2":{
      "scriptId":"u24"},
    "f47b66e63d93491796084d83a94971fb":{
      "scriptId":"u25"},
    "28b47998011048ef95d56ba3aa254f59":{
      "scriptId":"u26"},
    "405a88da932040ea9e222c7fb7bf0519":{
      "scriptId":"u27"},
    "41d1c2740700424bbfbe5f1e4d1eb6b3":{
      "scriptId":"u28"},
    "b3b16f2fbd2a49418382d78ee4bf184b":{
      "scriptId":"u29"},
    "79f3ab3c5b9845ae86e92f37bd193158":{
      "scriptId":"u30"},
    "20ca457487ab441982964212e1fa4690":{
      "scriptId":"u31"},
    "116e7c417b834910b6d927c797c1223d":{
      "scriptId":"u32"},
    "1ea46bc69c55446babf623d05a3daf6a":{
      "scriptId":"u33"},
    "bc3ebb3a71a642baa9df5cccb78b8f20":{
      "scriptId":"u34"},
    "3fc2ad06cb4f417ba3589b9355260d0a":{
      "scriptId":"u35"},
    "ea1d9a5e7feb4f418be0090bbd89b300":{
      "scriptId":"u36"},
    "c2d349aa529341858b9b1b6fb07cf9dd":{
      "scriptId":"u37"},
    "4e4add97c14e400ca21590c209225fe8":{
      "scriptId":"u38"},
    "1e154668414d4031bb77bc642965388a":{
      "scriptId":"u39"},
    "0deac709d0c14befa28c2b5d4f63ce6e":{
      "scriptId":"u40"},
    "53eb3afa12074e219e929470163410a0":{
      "scriptId":"u41"},
    "e764082176654a30b8f88cf00f1263d3":{
      "scriptId":"u42"},
    "0619b339c28142408f3a66061919da0b":{
      "scriptId":"u43"},
    "d2b5284e56a842de88d4e7d718e1faaa":{
      "scriptId":"u44"},
    "ad573e6852084684b60cf30fb66c045e":{
      "scriptId":"u45"},
    "65a5fd0fc4874ec4b07c65ee440c39e3":{
      "scriptId":"u46"},
    "73835c35b53e4aceb37f40605e11bc3a":{
      "scriptId":"u47"},
    "34bc9a24b5d241d8ac376d2c0fc33e56":{
      "scriptId":"u48"},
    "8965a7d904d04f9784568c7151d05874":{
      "scriptId":"u49"},
    "c54863f5d85c4fb7855e55225a7cf9b0":{
      "scriptId":"u50"},
    "a08c91ba6631417fac99eea92b65bfec":{
      "scriptId":"u51"},
    "8baac80b9ce4484cb891eec842c1d577":{
      "scriptId":"u52"},
    "04783517b4a04a8d8983ef192f6de932":{
      "scriptId":"u53"},
    "9b73841f46084476b1dc36e1ff8c5ad6":{
      "scriptId":"u54"},
    "8411b09345a9489cb2248dd40adef1fe":{
      "scriptId":"u55"},
    "4316d48218a04bb18bcfb557621334d4":{
      "scriptId":"u56"},
    "46d71cc3fb0442f99985cc198fecf042":{
      "scriptId":"u57"},
    "3ccbcdeae870410994448955f6c474d4":{
      "scriptId":"u58"},
    "1c8896a6d744414ead0340fe1cf6d430":{
      "scriptId":"u59"},
    "e686811e4a46401a936ef017d1810033":{
      "scriptId":"u60"},
    "ed2c3451a41545bd91d2462dd95fddfb":{
      "scriptId":"u61"}}});