$axure.loadCurrentPage({
  "url":"中国大学生在线.html",
  "generationDate":new Date(1417659389665.06),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b13f34eecc52457ead37dd7ed86fe17a",
    "type":"Axure:Page",
    "name":"中国大学生在线",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5f81fdd96f0d4929b787e2f69bd0dbff",
          "label":"背景",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":399,
              "height":745}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67a730e60be249c7a5bd8d1a4c822ac3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":399,
                  "height":745}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/中国大学生在线/背景_u0.png"}},
{
          "id":"c184257d388b4aeebf8d6a0c9d57a97d",
          "label":"引导页",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":139},
            "size":{
              "width":315,
              "height":455}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"59c5066a7ce44b66886d9395a414f6a9",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"b2455e9519f647e78221632dbd472049",
                  "label":"引导1",
                  "parentDynamicPanel":"c184257d388b4aeebf8d6a0c9d57a97d",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontSize":"36px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF333333,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":-10},
                    "size":{
                      "width":315,
                      "height":465}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b8c0913b86d04959925bc80f834d845c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c184257d388b4aeebf8d6a0c9d57a97d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"36px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF333333,
                          "opacity":1},
                        "location":{
                          "x":0,
                          "y":-10},
                        "size":{
                          "width":315,
                          "height":465}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"moveWidget",
                              "description":"移动 引导1 相对位置为 (-315,0) 线性 500ms,<br>引导2 相对位置为 (-315,0) 线性 500ms,<br>引导3 相对位置为 (-315,0) 线性 500ms",
                              "objectsToMoves":[{
                                  "objectPath":["b2455e9519f647e78221632dbd472049"],
                                  "moveInfo":{
                                    "moveType":"delta",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"-315",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "options":{
                                      "easing":"linear",
                                      "duration":500}}},
{
                                  "objectPath":["a1c5f901703242929152c0c958fc893c"],
                                  "moveInfo":{
                                    "moveType":"delta",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"-315",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "options":{
                                      "easing":"linear",
                                      "duration":500}}},
{
                                  "objectPath":["159c4ebb7148451db5e2ba592307dbf6"],
                                  "moveInfo":{
                                    "moveType":"delta",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"-315",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "options":{
                                      "easing":"linear",
                                      "duration":500}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/中国大学生在线/引导1_u3.png"}},
{
                  "id":"a1c5f901703242929152c0c958fc893c",
                  "label":"引导2",
                  "parentDynamicPanel":"c184257d388b4aeebf8d6a0c9d57a97d",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontSize":"36px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF333333,
                      "opacity":1},
                    "location":{
                      "x":315,
                      "y":0},
                    "size":{
                      "width":315,
                      "height":455}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"64ac43cbf7cb44eeae17ef7de1768a01",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c184257d388b4aeebf8d6a0c9d57a97d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"36px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF333333,
                          "opacity":1},
                        "location":{
                          "x":315,
                          "y":0},
                        "size":{
                          "width":315,
                          "height":455}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"moveWidget",
                              "description":"移动 引导2 相对位置为 (-315,0) 线性 500ms,<br>引导3 相对位置为 (-315,0) 线性 500ms",
                              "objectsToMoves":[{
                                  "objectPath":["a1c5f901703242929152c0c958fc893c"],
                                  "moveInfo":{
                                    "moveType":"delta",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"-315",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "options":{
                                      "easing":"linear",
                                      "duration":500}}},
{
                                  "objectPath":["159c4ebb7148451db5e2ba592307dbf6"],
                                  "moveInfo":{
                                    "moveType":"delta",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"-315",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "options":{
                                      "easing":"linear",
                                      "duration":500}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/中国大学生在线/引导2_u5.png"}},
{
                  "id":"159c4ebb7148451db5e2ba592307dbf6",
                  "label":"引导3",
                  "parentDynamicPanel":"c184257d388b4aeebf8d6a0c9d57a97d",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontSize":"36px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF333333,
                      "opacity":1},
                    "location":{
                      "x":630,
                      "y":0},
                    "size":{
                      "width":315,
                      "height":455}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8b9177e095ca4c0fa8e4c919739a3eb9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c184257d388b4aeebf8d6a0c9d57a97d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"36px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF333333,
                          "opacity":1},
                        "location":{
                          "x":630,
                          "y":0},
                        "size":{
                          "width":315,
                          "height":455}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 首页--未登录",
                              "target":{
                                "targetType":"page",
                                "url":"首页--未登录.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/中国大学生在线/引导2_u5.png"}}]}]},
{
          "id":"3d3a13a79fd24a728004141628f30e23",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":409,
              "y":237},
            "size":{
              "width":341,
              "height":66}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b63606e8f5649cdb48071ad04534ed8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":409,
                  "y":237},
                "size":{
                  "width":341,
                  "height":66}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "5f81fdd96f0d4929b787e2f69bd0dbff":{
      "scriptId":"u0"},
    "67a730e60be249c7a5bd8d1a4c822ac3":{
      "scriptId":"u1"},
    "c184257d388b4aeebf8d6a0c9d57a97d":{
      "scriptId":"u2"},
    "b2455e9519f647e78221632dbd472049":{
      "scriptId":"u3"},
    "b8c0913b86d04959925bc80f834d845c":{
      "scriptId":"u4"},
    "a1c5f901703242929152c0c958fc893c":{
      "scriptId":"u5"},
    "64ac43cbf7cb44eeae17ef7de1768a01":{
      "scriptId":"u6"},
    "159c4ebb7148451db5e2ba592307dbf6":{
      "scriptId":"u7"},
    "8b9177e095ca4c0fa8e4c919739a3eb9":{
      "scriptId":"u8"},
    "3d3a13a79fd24a728004141628f30e23":{
      "scriptId":"u9"},
    "1b63606e8f5649cdb48071ad04534ed8":{
      "scriptId":"u10"}}});