$axure.loadCurrentPage({
  "url":"验证手机.html",
  "generationDate":new Date(1417659390945.13),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"dc0b09cd4c464c08a2e3a38844da80e2",
    "type":"Axure:Page",
    "name":"验证手机",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a0dd9a48b7b94cb8869c96dfc2022779",
          "label":"背景",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":399,
              "height":745}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba35b7df94814966bf18e771dbc14ab1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":399,
                  "height":745}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/中国大学生在线/背景_u0.png"}},
{
          "id":"2880c0085c7340f6ae01c20cee556408",
          "label":"头部",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFEB1015},
            "location":{
              "x":35,
              "y":138},
            "size":{
              "width":319,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4a6e1e19f8f41cd9ca66145652c41de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEB1015},
                "location":{
                  "x":35,
                  "y":138},
                "size":{
                  "width":319,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页--未登录/头部_u2.png"}},
{
          "id":"423c728711324b8c82cac7823bf74c18",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":38,
              "y":142},
            "size":{
              "width":13,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b03d112426e409f9dae00f2c2b0d2c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":38,
                  "y":142},
                "size":{
                  "width":13,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 账号与安全",
                      "target":{
                        "targetType":"page",
                        "url":"账号与安全.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e37c5ddb5e4445d29ca56fe3ae8b6e93",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":290},
            "size":{
              "width":230,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/验证手机/u6_line.png"}},
{
          "id":"9654534b1f044d398673b6c64507d2fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":119,
              "y":232},
            "size":{
              "width":114,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c282ea590a254f21a6f3aea6f859a0e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":119,
                  "y":232},
                "size":{
                  "width":114,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"966565954cb54ceba4f73622d49e3c9f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":91,
              "y":269},
            "size":{
              "width":32,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"793b184c1ae345ed8d5e532e1191cad6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":91,
                  "y":269},
                "size":{
                  "width":32,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"658c017e5018430db7570fd90179f3b2",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":288,
              "y":142},
            "size":{
              "width":64,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"4ed6fb1d8f284ad99b9a2abdfbac0b82",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":71,
              "y":425},
            "size":{
              "width":268,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca3c586d175049efa5f6b351e3d4bdd9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":71,
                  "y":425},
                "size":{
                  "width":268,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bd063fbd60294289927564766fdc48c3",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":137,
              "y":265},
            "size":{
              "width":145,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"请输入手机号"},
{
          "id":"3e7f6ed94f794fe283b571947469691e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":61,
              "y":143},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"430efb9378e949b598b6cab6d8d1eb18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":61,
                  "y":143},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9fc2d78621854762acda3a09d05d12ff",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":350},
            "size":{
              "width":229,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/验证手机/u17_line.png"}},
{
          "id":"07ebfdc33e4644c9ba461a56b88c13d0",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":230,
              "y":316},
            "size":{
              "width":79,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b7bc74c96f0e4f919d5408ebb3a7cedb",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":316},
            "size":{
              "width":129,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"验证码"}]}},
  "masters":{
},
  "objectPaths":{
    "a0dd9a48b7b94cb8869c96dfc2022779":{
      "scriptId":"u0"},
    "ba35b7df94814966bf18e771dbc14ab1":{
      "scriptId":"u1"},
    "2880c0085c7340f6ae01c20cee556408":{
      "scriptId":"u2"},
    "d4a6e1e19f8f41cd9ca66145652c41de":{
      "scriptId":"u3"},
    "423c728711324b8c82cac7823bf74c18":{
      "scriptId":"u4"},
    "0b03d112426e409f9dae00f2c2b0d2c2":{
      "scriptId":"u5"},
    "e37c5ddb5e4445d29ca56fe3ae8b6e93":{
      "scriptId":"u6"},
    "9654534b1f044d398673b6c64507d2fe":{
      "scriptId":"u7"},
    "c282ea590a254f21a6f3aea6f859a0e2":{
      "scriptId":"u8"},
    "966565954cb54ceba4f73622d49e3c9f":{
      "scriptId":"u9"},
    "793b184c1ae345ed8d5e532e1191cad6":{
      "scriptId":"u10"},
    "658c017e5018430db7570fd90179f3b2":{
      "scriptId":"u11"},
    "4ed6fb1d8f284ad99b9a2abdfbac0b82":{
      "scriptId":"u12"},
    "ca3c586d175049efa5f6b351e3d4bdd9":{
      "scriptId":"u13"},
    "bd063fbd60294289927564766fdc48c3":{
      "scriptId":"u14"},
    "3e7f6ed94f794fe283b571947469691e":{
      "scriptId":"u15"},
    "430efb9378e949b598b6cab6d8d1eb18":{
      "scriptId":"u16"},
    "9fc2d78621854762acda3a09d05d12ff":{
      "scriptId":"u17"},
    "07ebfdc33e4644c9ba461a56b88c13d0":{
      "scriptId":"u18"},
    "b7bc74c96f0e4f919d5408ebb3a7cedb":{
      "scriptId":"u19"}}});