$axure.loadCurrentPage({
  "url":"账号与安全.html",
  "generationDate":new Date(1417659390914.13),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"142cf81a157d4d6aa403d6b74caf630d",
    "type":"Axure:Page",
    "name":"账号与安全",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8620167f0a514f9b8671aacfca06bb63",
          "label":"背景",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":399,
              "height":745}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3fbc2b167894071a6442b1a154dc054",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":399,
                  "height":745}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/中国大学生在线/背景_u0.png"}},
{
          "id":"87d5557374e14d81a90b7f03a9430218",
          "label":"头部",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFEB1015},
            "location":{
              "x":35,
              "y":138},
            "size":{
              "width":319,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"164f2360ae4542278347a16f87c5bcf9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEB1015},
                "location":{
                  "x":35,
                  "y":138},
                "size":{
                  "width":319,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页--未登录/头部_u2.png"}},
{
          "id":"da0e0068a0ea4a98a7d1e45a6c1ba800",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":38,
              "y":142},
            "size":{
              "width":13,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"280c99764eee442bbb0250573c758d55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":38,
                  "y":142},
                "size":{
                  "width":13,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 全局页面--已登录",
                      "target":{
                        "targetType":"page",
                        "url":"全局页面--已登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4cff7a631e2f4a93bd30377f45558d34",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":119,
              "y":232},
            "size":{
              "width":114,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f0de9abc938453eb2c4a91f34eccf0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":119,
                  "y":232},
                "size":{
                  "width":114,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"58412ecc054c4917be98c86847230248",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":420,
              "y":106},
            "size":{
              "width":381,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76a43800d89a4f1c8804713a5d82888b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":420,
                  "y":106},
                "size":{
                  "width":381,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e64522def895439d8395302f491e2aa3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":420,
              "y":190},
            "size":{
              "width":313,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5130c3a4574848298ddc0bed3648ff10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":420,
                  "y":190},
                "size":{
                  "width":313,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"37e67fecc32342f1896a2bec56d4a4df",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":420,
              "y":232},
            "size":{
              "width":456,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33f3ebbe2e99478ca840fa0b7376830b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":420,
                  "y":232},
                "size":{
                  "width":456,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"866087b3ae1544a7b6cdfe9454204e94",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":37,
              "y":185},
            "size":{
              "width":316,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd26095a1da34c9cbeba68b6f2d9214d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":37,
                  "y":185},
                "size":{
                  "width":316,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账号与安全/u14.png"}},
{
          "id":"ee2807ce6e1f4e0ea16929f494d6d76b",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":35,
              "y":185},
            "size":{
              "width":318,
              "height":41}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 验证手机",
                      "target":{
                        "targetType":"page",
                        "url":"验证手机.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"31a0b88401354acaae2ec0d3559c68cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":61,
              "y":147},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd17e7832a0040649c5567b9e363fbcd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":61,
                  "y":147},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25de61cdafae4fcdaebfb86768baac4f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":56,
              "y":144},
            "size":{
              "width":81,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5423aec307714fe3aec5832eecb96c42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":56,
                  "y":144},
                "size":{
                  "width":81,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"62cbd721c9a14364b66d33e296aac17f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":399,
              "y":409},
            "size":{
              "width":353,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80891d4bd69d4f58ac4552a43c773bea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":399,
                  "y":409},
                "size":{
                  "width":353,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fbf61c836c28432caa5d48660dc0414d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":66,
              "y":197},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f567a58bfeb429d94db3f3dbec83c0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":66,
                  "y":197},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9a2c5dd7cd9c4700b97149199f04284c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":155,
              "y":197},
            "size":{
              "width":100,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2d6a86b1cd3486ba7992a20be675b44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":155,
                  "y":197},
                "size":{
                  "width":100,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2624fd5c1a224ab2a06a3e5591fc39d1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":312,
              "y":195},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e516479880974003ac1c7d2d61ed921a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":312,
                  "y":195},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑校内信息页/u53.png"}},
{
          "id":"579a40234af14f1d8074f51bf2136845",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":37,
              "y":229},
            "size":{
              "width":316,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eed6e36c7f3c4b53823e5b5f738f6cd3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":37,
                  "y":229},
                "size":{
                  "width":316,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账号与安全/u14.png"}},
{
          "id":"ef7796f133e94ca085b705960e4279bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":66,
              "y":240},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05de7b6df5564176878c98a9bf08b26d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":66,
                  "y":240},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d4df50f12e544174a909de9b4ae171cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":155,
              "y":240},
            "size":{
              "width":150,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afd13b5ac4ad47f3adb679ba0fe8f2d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":155,
                  "y":240},
                "size":{
                  "width":150,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5f995f7aa4b04a52b2d35864d61be07f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":37,
              "y":309},
            "size":{
              "width":316,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76b306569973428ea20b8970bf85e213",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":37,
                  "y":309},
                "size":{
                  "width":316,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账号与安全/u14.png"}},
{
          "id":"f6fb955e866b4d0eb44892a43d9e55da",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":66,
              "y":320},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d4c885bde1042a9834fe0b9289c5add",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":66,
                  "y":320},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"91e25fe3dfc94b0da9439d4b42225cf8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":318},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"522e90df4b914024a462ea1c0f70c28d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":318},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑校内信息页/u53.png"}},
{
          "id":"1a3a757db4d143e782db4cbf3689dcdf",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":35,
              "y":309},
            "size":{
              "width":318,
              "height":41}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 修改密码",
                      "target":{
                        "targetType":"page",
                        "url":"修改密码.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"3e4855975064430fa30021e5ddbcdfe0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":420,
              "y":291},
            "size":{
              "width":200,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60dc5caab6af41ed84c4470f60b55399",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":420,
                  "y":291},
                "size":{
                  "width":200,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账号与安全/u42.png"}},
{
          "id":"3ec1a2b91c3a4d21a7463be60a13a086",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":317},
            "size":{
              "width":180,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/账号与安全/u44_line.png"}},
{
          "id":"b4ccd7c47775455cabc4f558f18d4ebe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":432,
              "y":300},
            "size":{
              "width":170,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd72116b4d3c42b29530901d6db00383",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":432,
                  "y":300},
                "size":{
                  "width":170,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"24535813754448e18712be770cc77c4d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":427,
              "y":327},
            "size":{
              "width":187,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"459efa7558da4116b981bf9b92794ec9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":427,
                  "y":327},
                "size":{
                  "width":187,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账号与安全/u47.png"}},
{
          "id":"807f982321be47b189200d0b89b3c958",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":446,
              "y":367},
            "size":{
              "width":53,
              "height":29},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53ae833ec5294383941a51f0a306e299",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":446,
                  "y":367},
                "size":{
                  "width":53,
                  "height":29},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账号与安全/u49.png"}},
{
          "id":"034de332e9bf4a14b8aca2f635c07e0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":538,
              "y":367},
            "size":{
              "width":53,
              "height":29},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"344a5db9872340eba3206aee11be2bf1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":538,
                  "y":367},
                "size":{
                  "width":53,
                  "height":29},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账号与安全/u49.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "8620167f0a514f9b8671aacfca06bb63":{
      "scriptId":"u0"},
    "d3fbc2b167894071a6442b1a154dc054":{
      "scriptId":"u1"},
    "87d5557374e14d81a90b7f03a9430218":{
      "scriptId":"u2"},
    "164f2360ae4542278347a16f87c5bcf9":{
      "scriptId":"u3"},
    "da0e0068a0ea4a98a7d1e45a6c1ba800":{
      "scriptId":"u4"},
    "280c99764eee442bbb0250573c758d55":{
      "scriptId":"u5"},
    "4cff7a631e2f4a93bd30377f45558d34":{
      "scriptId":"u6"},
    "5f0de9abc938453eb2c4a91f34eccf0b":{
      "scriptId":"u7"},
    "58412ecc054c4917be98c86847230248":{
      "scriptId":"u8"},
    "76a43800d89a4f1c8804713a5d82888b":{
      "scriptId":"u9"},
    "e64522def895439d8395302f491e2aa3":{
      "scriptId":"u10"},
    "5130c3a4574848298ddc0bed3648ff10":{
      "scriptId":"u11"},
    "37e67fecc32342f1896a2bec56d4a4df":{
      "scriptId":"u12"},
    "33f3ebbe2e99478ca840fa0b7376830b":{
      "scriptId":"u13"},
    "866087b3ae1544a7b6cdfe9454204e94":{
      "scriptId":"u14"},
    "fd26095a1da34c9cbeba68b6f2d9214d":{
      "scriptId":"u15"},
    "ee2807ce6e1f4e0ea16929f494d6d76b":{
      "scriptId":"u16"},
    "31a0b88401354acaae2ec0d3559c68cb":{
      "scriptId":"u17"},
    "fd17e7832a0040649c5567b9e363fbcd":{
      "scriptId":"u18"},
    "25de61cdafae4fcdaebfb86768baac4f":{
      "scriptId":"u19"},
    "5423aec307714fe3aec5832eecb96c42":{
      "scriptId":"u20"},
    "62cbd721c9a14364b66d33e296aac17f":{
      "scriptId":"u21"},
    "80891d4bd69d4f58ac4552a43c773bea":{
      "scriptId":"u22"},
    "fbf61c836c28432caa5d48660dc0414d":{
      "scriptId":"u23"},
    "3f567a58bfeb429d94db3f3dbec83c0a":{
      "scriptId":"u24"},
    "9a2c5dd7cd9c4700b97149199f04284c":{
      "scriptId":"u25"},
    "d2d6a86b1cd3486ba7992a20be675b44":{
      "scriptId":"u26"},
    "2624fd5c1a224ab2a06a3e5591fc39d1":{
      "scriptId":"u27"},
    "e516479880974003ac1c7d2d61ed921a":{
      "scriptId":"u28"},
    "579a40234af14f1d8074f51bf2136845":{
      "scriptId":"u29"},
    "eed6e36c7f3c4b53823e5b5f738f6cd3":{
      "scriptId":"u30"},
    "ef7796f133e94ca085b705960e4279bf":{
      "scriptId":"u31"},
    "05de7b6df5564176878c98a9bf08b26d":{
      "scriptId":"u32"},
    "d4df50f12e544174a909de9b4ae171cb":{
      "scriptId":"u33"},
    "afd13b5ac4ad47f3adb679ba0fe8f2d5":{
      "scriptId":"u34"},
    "5f995f7aa4b04a52b2d35864d61be07f":{
      "scriptId":"u35"},
    "76b306569973428ea20b8970bf85e213":{
      "scriptId":"u36"},
    "f6fb955e866b4d0eb44892a43d9e55da":{
      "scriptId":"u37"},
    "8d4c885bde1042a9834fe0b9289c5add":{
      "scriptId":"u38"},
    "91e25fe3dfc94b0da9439d4b42225cf8":{
      "scriptId":"u39"},
    "522e90df4b914024a462ea1c0f70c28d":{
      "scriptId":"u40"},
    "1a3a757db4d143e782db4cbf3689dcdf":{
      "scriptId":"u41"},
    "3e4855975064430fa30021e5ddbcdfe0":{
      "scriptId":"u42"},
    "60dc5caab6af41ed84c4470f60b55399":{
      "scriptId":"u43"},
    "3ec1a2b91c3a4d21a7463be60a13a086":{
      "scriptId":"u44"},
    "b4ccd7c47775455cabc4f558f18d4ebe":{
      "scriptId":"u45"},
    "cd72116b4d3c42b29530901d6db00383":{
      "scriptId":"u46"},
    "24535813754448e18712be770cc77c4d":{
      "scriptId":"u47"},
    "459efa7558da4116b981bf9b92794ec9":{
      "scriptId":"u48"},
    "807f982321be47b189200d0b89b3c958":{
      "scriptId":"u49"},
    "53ae833ec5294383941a51f0a306e299":{
      "scriptId":"u50"},
    "034de332e9bf4a14b8aca2f635c07e0a":{
      "scriptId":"u51"},
    "344a5db9872340eba3206aee11be2bf1":{
      "scriptId":"u52"}}});