$axure.loadCurrentPage({
  "url":"系统设置.html",
  "generationDate":new Date(1417659391026.13),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"882fbac0d6b247be8e436e9b1fc60ef5",
    "type":"Axure:Page",
    "name":"系统设置",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b0c0d532cff34192a09b5e3909582a38",
          "label":"背景",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":399,
              "height":745}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1682b6f5c16a471da2194a9bb8f60fe4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":399,
                  "height":745}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/中国大学生在线/背景_u0.png"}},
{
          "id":"736c0dc689aa4f48b4c549e08fd365a8",
          "label":"头部",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFEB1015},
            "location":{
              "x":35,
              "y":138},
            "size":{
              "width":319,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9aea009beb7c40e284143c4ff5e9c6d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEB1015},
                "location":{
                  "x":35,
                  "y":138},
                "size":{
                  "width":319,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页--未登录/头部_u2.png"}},
{
          "id":"c20f3ae302a3482eb20547503f0e1011",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":84,
              "y":226},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa1860974dc04999a711e01756e3cbaf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":84,
                  "y":226},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d14ce1920bfd48c0bf7ca1a746528e48",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":58,
              "y":188},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f89027f4f2b43c2ae10765a2f888f5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":58,
                  "y":188},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8eb18ebff42b4c4ea3e51005c9e61caf",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":204},
            "size":{
              "width":272,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF949494}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/系统设置/u8_line.png"}},
{
          "id":"eb65c3434e83495e853a66241033de10",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":260},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95036f332aba44f28ea367cfb3666738",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":58,
                  "y":260},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e92019bc0124002827d161ccf443b25",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF00FF00},
            "location":{
              "x":280,
              "y":260},
            "size":{
              "width":52,
              "height":19},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c2dbd5bf8fb4a7d8ce6a55f975088b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FF00},
                "location":{
                  "x":280,
                  "y":260},
                "size":{
                  "width":52,
                  "height":19},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/系统设置/u11.png"}},
{
          "id":"25289613870f40eab27c4972191ccd53",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF949494},
            "location":{
              "x":312,
              "y":260},
            "size":{
              "width":19,
              "height":19},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59dbd344a91641faa51de1a4a6272796",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF949494},
                "location":{
                  "x":312,
                  "y":260},
                "size":{
                  "width":19,
                  "height":19},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/系统设置/u13.png"}},
{
          "id":"b371c12ba1b0429a8654b733ec4aa003",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":297},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1267ec57bee2429390be07c37def0032",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":58,
                  "y":297},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"92a36cf0c7e749c3b2be1f3db8d979c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":297},
            "size":{
              "width":39,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0160df603bdc4959a1aabbf64b1e5376",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":297},
                "size":{
                  "width":39,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"515b772696f84bd4b78ad0fccd6acbed",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":321,
              "y":297},
            "size":{
              "width":9,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abc20e764d06406f8f4773ff94d8a3d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":321,
                  "y":297},
                "size":{
                  "width":9,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3085b19d264f4d06b18a86039c9c86cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":226},
            "size":{
              "width":248,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afe43aac6f6a4ea7a93d56801ec6db7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":226},
                "size":{
                  "width":248,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"14679e528df24ae188d1462c45dd0bb5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":297},
            "size":{
              "width":274,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3900dc7653842e4a2646d8c66f520e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":297},
                "size":{
                  "width":274,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c0640e69de5441a5a0873574c09a6dfd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":263},
            "size":{
              "width":235,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fddf7f56cb9e428787afc73fe4f9ae24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":263},
                "size":{
                  "width":235,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1937cd20313e4953a82639d1d6cbaf1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":38,
              "y":142},
            "size":{
              "width":13,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77eb0e8bc49642a7bf98774b390ddc32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":38,
                  "y":142},
                "size":{
                  "width":13,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 全局页面--已登录",
                      "target":{
                        "targetType":"page",
                        "url":"全局页面--已登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c18bcd5387c84db2a7bf0a2efd1ee499",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":56,
              "y":144},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b9995d83ebe4a6faa4d670c95898c4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":56,
                  "y":144},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"79f35f5f8f6a4c6a9dd77a4e64986c3a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":263,
              "y":223},
            "size":{
              "width":70,
              "height":22},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ebdd3fd56cb1431280dfb7e1f8aeb7b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":263,
                  "y":223},
                "size":{
                  "width":70,
                  "height":22},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/系统设置/u31.png"}},
{
          "id":"4507a4ed080f4e97b9b2b572e69a54d0",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":282,
              "y":225},
            "size":{
              "width":10,
              "height":19}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/系统设置/u33_line.png"}},
{
          "id":"e77c0d5614bd4a2588063a4dd2027b01",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":306,
              "y":225},
            "size":{
              "width":10,
              "height":19}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/系统设置/u33_line.png"}},
{
          "id":"337b61831fe0423cb3cf6d94a0018cb7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":226},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61a1379ecbd5430a8193438e92fac5de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":226},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"457ad766be914cbe8eb5e0d7bbb080d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":293,
              "y":226},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"894a87b878cb4669be64150ac51e47d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":293,
                  "y":226},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c9e805468bdf47af984b60db1ae4e388",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":315,
              "y":226},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8082e027468143abaf26488ddff54111",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":315,
                  "y":226},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "b0c0d532cff34192a09b5e3909582a38":{
      "scriptId":"u0"},
    "1682b6f5c16a471da2194a9bb8f60fe4":{
      "scriptId":"u1"},
    "736c0dc689aa4f48b4c549e08fd365a8":{
      "scriptId":"u2"},
    "9aea009beb7c40e284143c4ff5e9c6d5":{
      "scriptId":"u3"},
    "c20f3ae302a3482eb20547503f0e1011":{
      "scriptId":"u4"},
    "aa1860974dc04999a711e01756e3cbaf":{
      "scriptId":"u5"},
    "d14ce1920bfd48c0bf7ca1a746528e48":{
      "scriptId":"u6"},
    "8f89027f4f2b43c2ae10765a2f888f5c":{
      "scriptId":"u7"},
    "8eb18ebff42b4c4ea3e51005c9e61caf":{
      "scriptId":"u8"},
    "eb65c3434e83495e853a66241033de10":{
      "scriptId":"u9"},
    "95036f332aba44f28ea367cfb3666738":{
      "scriptId":"u10"},
    "2e92019bc0124002827d161ccf443b25":{
      "scriptId":"u11"},
    "9c2dbd5bf8fb4a7d8ce6a55f975088b9":{
      "scriptId":"u12"},
    "25289613870f40eab27c4972191ccd53":{
      "scriptId":"u13"},
    "59dbd344a91641faa51de1a4a6272796":{
      "scriptId":"u14"},
    "b371c12ba1b0429a8654b733ec4aa003":{
      "scriptId":"u15"},
    "1267ec57bee2429390be07c37def0032":{
      "scriptId":"u16"},
    "92a36cf0c7e749c3b2be1f3db8d979c6":{
      "scriptId":"u17"},
    "0160df603bdc4959a1aabbf64b1e5376":{
      "scriptId":"u18"},
    "515b772696f84bd4b78ad0fccd6acbed":{
      "scriptId":"u19"},
    "abc20e764d06406f8f4773ff94d8a3d2":{
      "scriptId":"u20"},
    "3085b19d264f4d06b18a86039c9c86cf":{
      "scriptId":"u21"},
    "afe43aac6f6a4ea7a93d56801ec6db7e":{
      "scriptId":"u22"},
    "14679e528df24ae188d1462c45dd0bb5":{
      "scriptId":"u23"},
    "f3900dc7653842e4a2646d8c66f520e0":{
      "scriptId":"u24"},
    "c0640e69de5441a5a0873574c09a6dfd":{
      "scriptId":"u25"},
    "fddf7f56cb9e428787afc73fe4f9ae24":{
      "scriptId":"u26"},
    "1937cd20313e4953a82639d1d6cbaf1a":{
      "scriptId":"u27"},
    "77eb0e8bc49642a7bf98774b390ddc32":{
      "scriptId":"u28"},
    "c18bcd5387c84db2a7bf0a2efd1ee499":{
      "scriptId":"u29"},
    "8b9995d83ebe4a6faa4d670c95898c4c":{
      "scriptId":"u30"},
    "79f35f5f8f6a4c6a9dd77a4e64986c3a":{
      "scriptId":"u31"},
    "ebdd3fd56cb1431280dfb7e1f8aeb7b5":{
      "scriptId":"u32"},
    "4507a4ed080f4e97b9b2b572e69a54d0":{
      "scriptId":"u33"},
    "e77c0d5614bd4a2588063a4dd2027b01":{
      "scriptId":"u34"},
    "337b61831fe0423cb3cf6d94a0018cb7":{
      "scriptId":"u35"},
    "61a1379ecbd5430a8193438e92fac5de":{
      "scriptId":"u36"},
    "457ad766be914cbe8eb5e0d7bbb080d9":{
      "scriptId":"u37"},
    "894a87b878cb4669be64150ac51e47d9":{
      "scriptId":"u38"},
    "c9e805468bdf47af984b60db1ae4e388":{
      "scriptId":"u39"},
    "8082e027468143abaf26488ddff54111":{
      "scriptId":"u40"}}});