$axure.loadCurrentPage({
  "url":"设置新密码.html",
  "generationDate":new Date(1417659390443.1),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b8a11e3db4084fb4ad120844df2db3fb",
    "type":"Axure:Page",
    "name":"设置新密码",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"623c3fff38074cfe905a217cf5f4c76e",
          "label":"背景",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":399,
              "height":745}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01bc725e23fc47cfb1c4bc663682a495",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":399,
                  "height":745}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/中国大学生在线/背景_u0.png"}},
{
          "id":"669290fa5dd543ffbe0e5fe6b79a5247",
          "label":"头部",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFEB1015},
            "location":{
              "x":35,
              "y":138},
            "size":{
              "width":319,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18df0f4a8e4240deaf1d68a48a9ba1ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEB1015},
                "location":{
                  "x":35,
                  "y":138},
                "size":{
                  "width":319,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页--未登录/头部_u2.png"}},
{
          "id":"cc395c364c69483fb7dca05e1ba37272",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":38,
              "y":142},
            "size":{
              "width":13,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"025df4f384a9421da91079a9379ce162",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":38,
                  "y":142},
                "size":{
                  "width":13,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页--未登录",
                      "target":{
                        "targetType":"page",
                        "url":"首页--未登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0142569add714cc9acbf24b51df94127",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":93,
              "y":245},
            "size":{
              "width":217,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/手机注册页面/u6_line.png"}},
{
          "id":"85292c740fa74c689cf1522707f65ca9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":119,
              "y":232},
            "size":{
              "width":114,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6559a09cf94c42cc9265283fe8177f2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":119,
                  "y":232},
                "size":{
                  "width":114,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"74288a7bac4d40d3a60aad3995e6928e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":96,
              "y":224},
            "size":{
              "width":109,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37c9220b75e2465493032cec44cc35de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":96,
                  "y":224},
                "size":{
                  "width":109,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4b07d71db8644d94a08fe85a6ba948a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":409,
              "y":190},
            "size":{
              "width":300,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2d281b97ec4498384be961cd7ea5ffd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":409,
                  "y":190},
                "size":{
                  "width":300,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e9cc3150558a4360a8d4dea52c9a6834",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":237,
              "y":224},
            "size":{
              "width":79,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"6d5ba513972e4e08ac915ca5b7c6cdc9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":93,
              "y":353},
            "size":{
              "width":217,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/手机注册页面/u6_line.png"}},
{
          "id":"8295c10fa0ee4951b7035b690525ed6c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":167,
              "y":331},
            "size":{
              "width":154,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "linePattern":"none",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"944510bce74e4cdbabd47986d9d296da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":167,
                  "y":331},
                "size":{
                  "width":154,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "linePattern":"none",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"96aaf820c63748e79e7609ec4fbe5017",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":93,
              "y":331},
            "size":{
              "width":55,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44181a6b494f4c4981191851496d7003",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":93,
                  "y":331},
                "size":{
                  "width":55,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ec510e11f3164c2d998bea9277db1871",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":287,
              "y":141},
            "size":{
              "width":63,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 手机号登录",
                      "target":{
                        "targetType":"page",
                        "url":"手机号登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"730b550df09249dfb4062968c67665fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":62,
              "y":142},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff699b6b753749fbbe8287a8f90110b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":62,
                  "y":142},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3639b08ef8754c11840f226c45428e6c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":220.5,
              "y":265},
            "size":{
              "width":93,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b90766d4e8e413b83e9fe39d9c2f9be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220.5,
                  "y":265},
                "size":{
                  "width":93,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设置新密码/u22.jpg"}},
{
          "id":"082ee72857d4418b848efad268674155",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":89.5,
              "y":303},
            "size":{
              "width":217,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/手机注册页面/u6_line.png"}},
{
          "id":"81b58b88e31a4149ad9cb6d4fd23685f",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":89.5,
              "y":278},
            "size":{
              "width":110,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"验证字符"}]}},
  "masters":{
},
  "objectPaths":{
    "623c3fff38074cfe905a217cf5f4c76e":{
      "scriptId":"u0"},
    "01bc725e23fc47cfb1c4bc663682a495":{
      "scriptId":"u1"},
    "669290fa5dd543ffbe0e5fe6b79a5247":{
      "scriptId":"u2"},
    "18df0f4a8e4240deaf1d68a48a9ba1ad":{
      "scriptId":"u3"},
    "cc395c364c69483fb7dca05e1ba37272":{
      "scriptId":"u4"},
    "025df4f384a9421da91079a9379ce162":{
      "scriptId":"u5"},
    "0142569add714cc9acbf24b51df94127":{
      "scriptId":"u6"},
    "85292c740fa74c689cf1522707f65ca9":{
      "scriptId":"u7"},
    "6559a09cf94c42cc9265283fe8177f2a":{
      "scriptId":"u8"},
    "74288a7bac4d40d3a60aad3995e6928e":{
      "scriptId":"u9"},
    "37c9220b75e2465493032cec44cc35de":{
      "scriptId":"u10"},
    "4b07d71db8644d94a08fe85a6ba948a6":{
      "scriptId":"u11"},
    "a2d281b97ec4498384be961cd7ea5ffd":{
      "scriptId":"u12"},
    "e9cc3150558a4360a8d4dea52c9a6834":{
      "scriptId":"u13"},
    "6d5ba513972e4e08ac915ca5b7c6cdc9":{
      "scriptId":"u14"},
    "8295c10fa0ee4951b7035b690525ed6c":{
      "scriptId":"u15"},
    "944510bce74e4cdbabd47986d9d296da":{
      "scriptId":"u16"},
    "96aaf820c63748e79e7609ec4fbe5017":{
      "scriptId":"u17"},
    "44181a6b494f4c4981191851496d7003":{
      "scriptId":"u18"},
    "ec510e11f3164c2d998bea9277db1871":{
      "scriptId":"u19"},
    "730b550df09249dfb4062968c67665fc":{
      "scriptId":"u20"},
    "ff699b6b753749fbbe8287a8f90110b9":{
      "scriptId":"u21"},
    "3639b08ef8754c11840f226c45428e6c":{
      "scriptId":"u22"},
    "2b90766d4e8e413b83e9fe39d9c2f9be":{
      "scriptId":"u23"},
    "082ee72857d4418b848efad268674155":{
      "scriptId":"u24"},
    "81b58b88e31a4149ad9cb6d4fd23685f":{
      "scriptId":"u25"}}});