$axure.loadCurrentPage({
  "url":"全局页面--已登录.html",
  "generationDate":new Date(1417659390512.1),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1070a1e2e0f04eeabfaf1a93ff93b04a",
    "type":"Axure:Page",
    "name":"全局页面--已登录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"668ff031fd504178bfd7d67ff7e82ab5",
          "label":"背景",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":399,
              "height":745}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e9ee23319fc45c49ba1b25c02940a74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":399,
                  "height":745}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/中国大学生在线/背景_u0.png"}},
{
          "id":"f7633730c88d4cadb150cefe93f372b0",
          "label":"头部",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFEB1015},
            "location":{
              "x":35,
              "y":138},
            "size":{
              "width":319,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dbd7f5d2258e45dea6f63e9373b43ec8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEB1015},
                "location":{
                  "x":35,
                  "y":138},
                "size":{
                  "width":319,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页--未登录/头部_u2.png"}},
{
          "id":"cedcbdb45693466e9b8ab6b02b2217ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":38,
              "y":142},
            "size":{
              "width":13,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1d86db7e2d54cb69a1452d4e22ece3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":38,
                  "y":142},
                "size":{
                  "width":13,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页--登录",
                      "target":{
                        "targetType":"page",
                        "url":"首页--登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1fb2c8c87a6244089bc960fb3ea2b67c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":281},
            "size":{
              "width":270,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/全局页面--已登录/u6_line.png"}},
{
          "id":"9291920dee4c4327a4bc49aaffa7587c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":205},
            "size":{
              "width":66,
              "height":66},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb9f629750134db9b3dee12ef7ad5f21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":205},
                "size":{
                  "width":66,
                  "height":66},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 编辑个人信息页",
                      "target":{
                        "targetType":"page",
                        "url":"编辑个人信息页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/全局页面--已登录/u7.png"}},
{
          "id":"eec8958b38ac4b23bc546561bdee4ca1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":142,
              "y":217},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"941ef028694e46f4881151ade325ddf5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":142,
                  "y":217},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"344f8a0f336446af87d2b1a50f6cc510",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":409,
              "y":190},
            "size":{
              "width":300,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abacaa9965be447c851153b559fb2dc1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":409,
                  "y":190},
                "size":{
                  "width":300,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ae0e49606bc4657a411d36eb3aad897",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":132,
              "y":540},
            "size":{
              "width":125,
              "height":30},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ad609307f0f4a2f99170ce8e87e1e14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":132,
                  "y":540},
                "size":{
                  "width":125,
                  "height":30},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页--未登录",
                      "target":{
                        "targetType":"page",
                        "url":"首页--未登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/全局页面--已登录/u13.png"}},
{
          "id":"604b9fd2e74d4cd2b4043cb1dcb472ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":250,
              "y":243},
            "size":{
              "width":53,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18d2b6a0d3234e96b2f4dffe04acae3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":250,
                  "y":243},
                "size":{
                  "width":53,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e6fec17a5c284fac820e33bd041522d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":116,
              "y":351},
            "size":{
              "width":81,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9c26551233b4b6a9d2cc1123b36c0c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":116,
                  "y":351},
                "size":{
                  "width":81,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 账号与安全",
                      "target":{
                        "targetType":"page",
                        "url":"账号与安全.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f39508f333443b08c2fbd06da8c49b3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":83,
              "y":349},
            "size":{
              "width":23,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8da0ec51cdc14229be6634b2b8d1abfc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":83,
                  "y":349},
                "size":{
                  "width":23,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全局页面--已登录/u19.png"}},
{
          "id":"3a547ee7964a4e6982ea238afed3beb2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":116,
              "y":313},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2f8347f796d415d91891430e3af10af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":116,
                  "y":313},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 编辑校内信息页",
                      "target":{
                        "targetType":"page",
                        "url":"编辑校内信息页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1114266018e4467f8b9aa2ac80a9536e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":83,
              "y":311},
            "size":{
              "width":23,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ab6a6eca0ef4b11b2b62c3b64cfd3b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":83,
                  "y":311},
                "size":{
                  "width":23,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全局页面--已登录/u19.png"}},
{
          "id":"d6d1ccc0302c40138de3e16c17a677c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":116,
              "y":390},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"854a52100e2b4605874b05ef5ab1f175",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":116,
                  "y":390},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 系统设置",
                      "target":{
                        "targetType":"page",
                        "url":"系统设置.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c7ba6ec05af347ba8a15597485a84329",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":83,
              "y":388},
            "size":{
              "width":23,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"158dcc1cdf1649198b9fd6ddd733489b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":83,
                  "y":388},
                "size":{
                  "width":23,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全局页面--已登录/u19.png"}},
{
          "id":"bec4e41f9c054e15bc214b97ce17edc3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":142,
              "y":243},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ce73cc828d94e2d87048dc8f02693fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":142,
                  "y":243},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"543581fbd2344b728f18c0d361ea3525",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":262,
              "y":217},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ee92dec3368405dbd76eda851ebbb89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":262,
                  "y":217},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aed6f1479cf04de2bd9ef319d74f95c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":116,
              "y":432},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd4df33106b349bca3966148e9ec1bb5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":116,
                  "y":432},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 意见反馈",
                      "target":{
                        "targetType":"page",
                        "url":"意见反馈.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c5670d670e0a453cb4bf789a963f5f33",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":83,
              "y":430},
            "size":{
              "width":23,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a9807dde6394dce9f3d6bd809b5a846",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":83,
                  "y":430},
                "size":{
                  "width":23,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全局页面--已登录/u19.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "668ff031fd504178bfd7d67ff7e82ab5":{
      "scriptId":"u0"},
    "1e9ee23319fc45c49ba1b25c02940a74":{
      "scriptId":"u1"},
    "f7633730c88d4cadb150cefe93f372b0":{
      "scriptId":"u2"},
    "dbd7f5d2258e45dea6f63e9373b43ec8":{
      "scriptId":"u3"},
    "cedcbdb45693466e9b8ab6b02b2217ac":{
      "scriptId":"u4"},
    "b1d86db7e2d54cb69a1452d4e22ece3b":{
      "scriptId":"u5"},
    "1fb2c8c87a6244089bc960fb3ea2b67c":{
      "scriptId":"u6"},
    "9291920dee4c4327a4bc49aaffa7587c":{
      "scriptId":"u7"},
    "eb9f629750134db9b3dee12ef7ad5f21":{
      "scriptId":"u8"},
    "eec8958b38ac4b23bc546561bdee4ca1":{
      "scriptId":"u9"},
    "941ef028694e46f4881151ade325ddf5":{
      "scriptId":"u10"},
    "344f8a0f336446af87d2b1a50f6cc510":{
      "scriptId":"u11"},
    "abacaa9965be447c851153b559fb2dc1":{
      "scriptId":"u12"},
    "0ae0e49606bc4657a411d36eb3aad897":{
      "scriptId":"u13"},
    "6ad609307f0f4a2f99170ce8e87e1e14":{
      "scriptId":"u14"},
    "604b9fd2e74d4cd2b4043cb1dcb472ef":{
      "scriptId":"u15"},
    "18d2b6a0d3234e96b2f4dffe04acae3d":{
      "scriptId":"u16"},
    "e6fec17a5c284fac820e33bd041522d3":{
      "scriptId":"u17"},
    "a9c26551233b4b6a9d2cc1123b36c0c6":{
      "scriptId":"u18"},
    "1f39508f333443b08c2fbd06da8c49b3":{
      "scriptId":"u19"},
    "8da0ec51cdc14229be6634b2b8d1abfc":{
      "scriptId":"u20"},
    "3a547ee7964a4e6982ea238afed3beb2":{
      "scriptId":"u21"},
    "b2f8347f796d415d91891430e3af10af":{
      "scriptId":"u22"},
    "1114266018e4467f8b9aa2ac80a9536e":{
      "scriptId":"u23"},
    "2ab6a6eca0ef4b11b2b62c3b64cfd3b6":{
      "scriptId":"u24"},
    "d6d1ccc0302c40138de3e16c17a677c9":{
      "scriptId":"u25"},
    "854a52100e2b4605874b05ef5ab1f175":{
      "scriptId":"u26"},
    "c7ba6ec05af347ba8a15597485a84329":{
      "scriptId":"u27"},
    "158dcc1cdf1649198b9fd6ddd733489b":{
      "scriptId":"u28"},
    "bec4e41f9c054e15bc214b97ce17edc3":{
      "scriptId":"u29"},
    "3ce73cc828d94e2d87048dc8f02693fe":{
      "scriptId":"u30"},
    "543581fbd2344b728f18c0d361ea3525":{
      "scriptId":"u31"},
    "5ee92dec3368405dbd76eda851ebbb89":{
      "scriptId":"u32"},
    "aed6f1479cf04de2bd9ef319d74f95c5":{
      "scriptId":"u33"},
    "fd4df33106b349bca3966148e9ec1bb5":{
      "scriptId":"u34"},
    "c5670d670e0a453cb4bf789a963f5f33":{
      "scriptId":"u35"},
    "0a9807dde6394dce9f3d6bd809b5a846":{
      "scriptId":"u36"}}});