$axure.loadCurrentPage({
  "url":"账号密码找回.html",
  "generationDate":new Date(1417659390367.1),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b99e21f737f24cb2984bc4c96c125e35",
    "type":"Axure:Page",
    "name":"账号密码找回",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f8beaef3f58a47efbb8f763a86170881",
          "label":"背景",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":399,
              "height":745}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"effb006cc9fa40118ed713ee993d889b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":399,
                  "height":745}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/中国大学生在线/背景_u0.png"}},
{
          "id":"fca8fa8a39b34a57b8762b9a560da0f5",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":88,
              "y":255},
            "size":{
              "width":217,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/手机注册页面/u6_line.png"}},
{
          "id":"1f6cb372e3da4cf98f463643e50f10bf",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":125,
              "y":230},
            "size":{
              "width":145,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"请输入手机号"},
{
          "id":"22337ba5337a4c8c93d328628544ea6e",
          "label":"头部",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFEB1015},
            "location":{
              "x":35,
              "y":138},
            "size":{
              "width":319,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4dc2d19b9a8e4ee1b9df252a3dbdca8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEB1015},
                "location":{
                  "x":35,
                  "y":138},
                "size":{
                  "width":319,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页--未登录/头部_u2.png"}},
{
          "id":"312dd75ce8854e7b8189476e166cc7b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":38,
              "y":142},
            "size":{
              "width":13,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44907ef9782046fbb97c695acb90fff3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":38,
                  "y":142},
                "size":{
                  "width":13,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 账号登录页",
                      "target":{
                        "targetType":"page",
                        "url":"账号登录页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f64220a4fbb54b13a11ecca6f1ea37e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":57,
              "y":142},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b328011555ac4b44af5c8d97c9a7d987",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":57,
                  "y":142},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"127e107db7dd4238baaff141db7d2a6c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":141},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"1dab75a1b74e4b07ab31c47466bbb201",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":51,
              "y":210},
            "size":{
              "width":280,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/账号密码找回/u11_line.png"}},
{
          "id":"27ce05e14965497ca1461c5844866653",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Adobe 宋体 Std L Oblique', 'Adobe 宋体 Std'",
            "fontSize":"18px",
            "fontWeight":"300",
            "fontStyle":"oblique",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":51,
              "y":187},
            "size":{
              "width":145,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"请输入手机号"},
{
          "id":"78c3dc8e24314c5cac07614da09cebff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":51,
              "y":387},
            "size":{
              "width":280,
              "height":153}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1248712dfd2c4210a15b5d10fd82140c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":51,
                  "y":387},
                "size":{
                  "width":280,
                  "height":153}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账号密码找回/u13.png"}},
{
          "id":"e628502ff569499fb580078d2612a64c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":88,
              "y":415},
            "size":{
              "width":209,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f03b7955b82740b18688927b6d1a28f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":88,
                  "y":415},
                "size":{
                  "width":209,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"30dc8f6629314ab48f3ed129fa328c37",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":89,
              "y":490},
            "size":{
              "width":80,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93010b8493744e19be73545a89e53ad3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":89,
                  "y":490},
                "size":{
                  "width":80,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账号密码找回/u17.png"}},
{
          "id":"0dc47467f0ab4cdb86f0300783a33de2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":213,
              "y":489},
            "size":{
              "width":80,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d980caee5c74e8c9ff1d67315cffa98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":213,
                  "y":489},
                "size":{
                  "width":80,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账号密码找回/u17.png"}},
{
          "id":"de1d12dda8764495a764f227ff67c661",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":409,
              "y":260},
            "size":{
              "width":222,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"240191ce1ce040788a732bcd00f38fd3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":409,
                  "y":260},
                "size":{
                  "width":222,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "f8beaef3f58a47efbb8f763a86170881":{
      "scriptId":"u0"},
    "effb006cc9fa40118ed713ee993d889b":{
      "scriptId":"u1"},
    "fca8fa8a39b34a57b8762b9a560da0f5":{
      "scriptId":"u2"},
    "1f6cb372e3da4cf98f463643e50f10bf":{
      "scriptId":"u3"},
    "22337ba5337a4c8c93d328628544ea6e":{
      "scriptId":"u4"},
    "4dc2d19b9a8e4ee1b9df252a3dbdca8c":{
      "scriptId":"u5"},
    "312dd75ce8854e7b8189476e166cc7b3":{
      "scriptId":"u6"},
    "44907ef9782046fbb97c695acb90fff3":{
      "scriptId":"u7"},
    "f64220a4fbb54b13a11ecca6f1ea37e6":{
      "scriptId":"u8"},
    "b328011555ac4b44af5c8d97c9a7d987":{
      "scriptId":"u9"},
    "127e107db7dd4238baaff141db7d2a6c":{
      "scriptId":"u10"},
    "1dab75a1b74e4b07ab31c47466bbb201":{
      "scriptId":"u11"},
    "27ce05e14965497ca1461c5844866653":{
      "scriptId":"u12"},
    "78c3dc8e24314c5cac07614da09cebff":{
      "scriptId":"u13"},
    "1248712dfd2c4210a15b5d10fd82140c":{
      "scriptId":"u14"},
    "e628502ff569499fb580078d2612a64c":{
      "scriptId":"u15"},
    "f03b7955b82740b18688927b6d1a28f6":{
      "scriptId":"u16"},
    "30dc8f6629314ab48f3ed129fa328c37":{
      "scriptId":"u17"},
    "93010b8493744e19be73545a89e53ad3":{
      "scriptId":"u18"},
    "0dc47467f0ab4cdb86f0300783a33de2":{
      "scriptId":"u19"},
    "8d980caee5c74e8c9ff1d67315cffa98":{
      "scriptId":"u20"},
    "de1d12dda8764495a764f227ff67c661":{
      "scriptId":"u21"},
    "240191ce1ce040788a732bcd00f38fd3":{
      "scriptId":"u22"}}});