$axure.loadCurrentPage({
  "url":"全局页面--未登录.html",
  "generationDate":new Date(1417659390228.09),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"95c9d7bd035d42fbaaf71982231e1a64",
    "type":"Axure:Page",
    "name":"全局页面--未登录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"668ff031fd504178bfd7d67ff7e82ab5",
          "label":"背景",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":399,
              "height":745}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e9ee23319fc45c49ba1b25c02940a74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":399,
                  "height":745}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/中国大学生在线/背景_u0.png"}},
{
          "id":"f7633730c88d4cadb150cefe93f372b0",
          "label":"头部",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFEB1015},
            "location":{
              "x":35,
              "y":138},
            "size":{
              "width":319,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dbd7f5d2258e45dea6f63e9373b43ec8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEB1015},
                "location":{
                  "x":35,
                  "y":138},
                "size":{
                  "width":319,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页--未登录/头部_u2.png"}},
{
          "id":"cedcbdb45693466e9b8ab6b02b2217ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":38,
              "y":142},
            "size":{
              "width":13,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1d86db7e2d54cb69a1452d4e22ece3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":38,
                  "y":142},
                "size":{
                  "width":13,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页--未登录",
                      "target":{
                        "targetType":"page",
                        "url":"首页--未登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4df9eb55725a4a2cbf2791e9137413b1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":190},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c091652ebe894c559c9d1de6bac0f828",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":190},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 手机号登录",
                      "target":{
                        "targetType":"page",
                        "url":"手机号登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/全局页面--未登录/u6.png"}},
{
          "id":"7ab8d03554084b719af5cce9c35c6f13",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":155,
              "y":190},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f03d5defcece46f09b089e91002794b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":155,
                  "y":190},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 账号登录页",
                      "target":{
                        "targetType":"page",
                        "url":"账号登录页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/全局页面--未登录/u6.png"}},
{
          "id":"01ef069e503a4207999012cf8464714d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":229,
              "y":190},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7eb53b1e79164f8aa3e2a6cc56339a37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":229,
                  "y":190},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 QQ登录页",
                      "target":{
                        "targetType":"page",
                        "url":"qq登录页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/全局页面--未登录/u6.png"}},
{
          "id":"ca679fc9e14e4f3cb6663946cad85a4d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":304,
              "y":190},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8db421e7d3824e41bc77c3be982910ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":304,
                  "y":190},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 手机注册页面",
                      "target":{
                        "targetType":"page",
                        "url":"手机注册页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/全局页面--未登录/u6.png"}},
{
          "id":"9f65d117c5d34f25a37cda949c8f6eb1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":399,
              "y":370},
            "size":{
              "width":487,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f037e5aa84841859cd232c99ece53c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":399,
                  "y":370},
                "size":{
                  "width":487,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"50e4c7d9138e45d1bb54cf299e188d56",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":399,
              "y":314},
            "size":{
              "width":273,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a473ab3125a49aaa2721667f42c54c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":399,
                  "y":314},
                "size":{
                  "width":273,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全局页面--未登录/u16.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "668ff031fd504178bfd7d67ff7e82ab5":{
      "scriptId":"u0"},
    "1e9ee23319fc45c49ba1b25c02940a74":{
      "scriptId":"u1"},
    "f7633730c88d4cadb150cefe93f372b0":{
      "scriptId":"u2"},
    "dbd7f5d2258e45dea6f63e9373b43ec8":{
      "scriptId":"u3"},
    "cedcbdb45693466e9b8ab6b02b2217ac":{
      "scriptId":"u4"},
    "b1d86db7e2d54cb69a1452d4e22ece3b":{
      "scriptId":"u5"},
    "4df9eb55725a4a2cbf2791e9137413b1":{
      "scriptId":"u6"},
    "c091652ebe894c559c9d1de6bac0f828":{
      "scriptId":"u7"},
    "7ab8d03554084b719af5cce9c35c6f13":{
      "scriptId":"u8"},
    "f03d5defcece46f09b089e91002794b6":{
      "scriptId":"u9"},
    "01ef069e503a4207999012cf8464714d":{
      "scriptId":"u10"},
    "7eb53b1e79164f8aa3e2a6cc56339a37":{
      "scriptId":"u11"},
    "ca679fc9e14e4f3cb6663946cad85a4d":{
      "scriptId":"u12"},
    "8db421e7d3824e41bc77c3be982910ad":{
      "scriptId":"u13"},
    "9f65d117c5d34f25a37cda949c8f6eb1":{
      "scriptId":"u14"},
    "5f037e5aa84841859cd232c99ece53c0":{
      "scriptId":"u15"},
    "50e4c7d9138e45d1bb54cf299e188d56":{
      "scriptId":"u16"},
    "2a473ab3125a49aaa2721667f42c54c3":{
      "scriptId":"u17"}}});