$axure.loadCurrentPage({
  "url":"组图内容页.html",
  "generationDate":new Date(1417659391564.16),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1e4936a410e2409d9b8b462fb05aff28",
    "type":"Axure:Page",
    "name":"组图内容页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e932359b93104bcbb33875ec4bb380db",
          "label":"背景",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":399,
              "height":745}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1e4e2ba941646b5a83574f85dd76476",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":399,
                  "height":745}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/中国大学生在线/背景_u0.png"}},
{
          "id":"aa3c1d1cbb0b4921bbb02af6bee0a35c",
          "label":"头部",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFEB1015},
            "location":{
              "x":35,
              "y":138},
            "size":{
              "width":319,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06ded7d279794288880004febada506d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEB1015},
                "location":{
                  "x":35,
                  "y":138},
                "size":{
                  "width":319,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页--未登录/头部_u2.png"}},
{
          "id":"529f283f06204f73a3e262527351052f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":38,
              "y":142},
            "size":{
              "width":13,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43be7b5618b647fc816675be0f231e3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":38,
                  "y":142},
                "size":{
                  "width":13,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页--未登录",
                      "target":{
                        "targetType":"page",
                        "url":"首页--未登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"104bdef7780949dfbda9ce404b3952b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":48,
              "y":175},
            "size":{
              "width":225,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57e89318c0c7451f81c5360a306eb677",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":48,
                  "y":175},
                "size":{
                  "width":225,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2c465d85bfe747149edede6a42cef577",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":48,
              "y":205},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67c891676e3c4531b79ecca85a397fbc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":48,
                  "y":205},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"80c14c3b08844696bec5404f185703d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "location":{
              "x":120,
              "y":203},
            "size":{
              "width":82,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8cd1cfffd2bf45939172b6f61d370e11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "location":{
                  "x":120,
                  "y":203},
                "size":{
                  "width":82,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4e24dc558e2d44aa8b1fafed617b1fc3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":240},
            "size":{
              "width":294,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f07fc066db2d4f42a592f1f402c9c45e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":240},
                "size":{
                  "width":294,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新闻内容页/u14.png"}},
{
          "id":"92901e44fe7f470cafd852cc1d3a7e7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":380},
            "size":{
              "width":55,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b58856b329134aa4bb64818d4d23d6ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":380},
                "size":{
                  "width":55,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d019223753c40cf80d4f2fb52c63464",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":546},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"368d492305284c4fb60309d4704b2b1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":546},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b9b75711c7e140e6a1f987e8d159b6d5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":406},
            "size":{
              "width":294,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe64fc904bd14a32b761001a7469ebac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":406},
                "size":{
                  "width":294,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/组图内容页/u18.png"}},
{
          "id":"16ebc21c0e574853b3e4d3cd69eadda0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEEECE1},
            "location":{
              "x":36,
              "y":568},
            "size":{
              "width":317,
              "height":26},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da8a8a2045894cd6b100acb7b016af03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEEECE1},
                "location":{
                  "x":36,
                  "y":568},
                "size":{
                  "width":317,
                  "height":26},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新闻内容页/u16.png"}},
{
          "id":"96789b269bc84f46859fb77211c8f414",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":563},
            "size":{
              "width":317,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页--未登录/u4_line.png"}},
{
          "id":"07366e5b90214be98604fe33950b5441",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":329,
              "y":571.5},
            "size":{
              "width":18,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec6e6323caf34f33a6ec1183756e9075",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":329,
                  "y":571.5},
                "size":{
                  "width":18,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"切换 分享页面",
                      "objectsToFades":[{
                          "objectPath":["d0a98a1ded1646c4907d9092a56de2cb"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/新闻内容页/u19.png"}},
{
          "id":"d0a98a1ded1646c4907d9092a56de2cb",
          "label":"分享页面",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "location":{
              "x":36,
              "y":494},
            "size":{
              "width":317,
              "height":100},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d2f1dda730a4fa580ba908aa1f88356",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":36,
                  "y":494},
                "size":{
                  "width":317,
                  "height":100},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 分享页面",
                      "objectsToFades":[{
                          "objectPath":["d0a98a1ded1646c4907d9092a56de2cb"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7b8554d3710642f8a818cd0d62a1d8ea",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":569},
            "size":{
              "width":122,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea12359fcd474209bb16bac0cb99ef8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":569},
                "size":{
                  "width":122,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新闻内容页/u21.png"}},
{
          "id":"4a2cbd9936804e6bab39ec558fcb5c89",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":448,
              "y":254},
            "size":{
              "width":497,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24d39249329f42d89afd93c2b841c4dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":448,
                  "y":254},
                "size":{
                  "width":497,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "e932359b93104bcbb33875ec4bb380db":{
      "scriptId":"u0"},
    "e1e4e2ba941646b5a83574f85dd76476":{
      "scriptId":"u1"},
    "aa3c1d1cbb0b4921bbb02af6bee0a35c":{
      "scriptId":"u2"},
    "06ded7d279794288880004febada506d":{
      "scriptId":"u3"},
    "529f283f06204f73a3e262527351052f":{
      "scriptId":"u4"},
    "43be7b5618b647fc816675be0f231e3e":{
      "scriptId":"u5"},
    "104bdef7780949dfbda9ce404b3952b4":{
      "scriptId":"u6"},
    "57e89318c0c7451f81c5360a306eb677":{
      "scriptId":"u7"},
    "2c465d85bfe747149edede6a42cef577":{
      "scriptId":"u8"},
    "67c891676e3c4531b79ecca85a397fbc":{
      "scriptId":"u9"},
    "80c14c3b08844696bec5404f185703d3":{
      "scriptId":"u10"},
    "8cd1cfffd2bf45939172b6f61d370e11":{
      "scriptId":"u11"},
    "4e24dc558e2d44aa8b1fafed617b1fc3":{
      "scriptId":"u12"},
    "f07fc066db2d4f42a592f1f402c9c45e":{
      "scriptId":"u13"},
    "92901e44fe7f470cafd852cc1d3a7e7e":{
      "scriptId":"u14"},
    "b58856b329134aa4bb64818d4d23d6ca":{
      "scriptId":"u15"},
    "8d019223753c40cf80d4f2fb52c63464":{
      "scriptId":"u16"},
    "368d492305284c4fb60309d4704b2b1c":{
      "scriptId":"u17"},
    "b9b75711c7e140e6a1f987e8d159b6d5":{
      "scriptId":"u18"},
    "fe64fc904bd14a32b761001a7469ebac":{
      "scriptId":"u19"},
    "16ebc21c0e574853b3e4d3cd69eadda0":{
      "scriptId":"u20"},
    "da8a8a2045894cd6b100acb7b016af03":{
      "scriptId":"u21"},
    "96789b269bc84f46859fb77211c8f414":{
      "scriptId":"u22"},
    "07366e5b90214be98604fe33950b5441":{
      "scriptId":"u23"},
    "ec6e6323caf34f33a6ec1183756e9075":{
      "scriptId":"u24"},
    "d0a98a1ded1646c4907d9092a56de2cb":{
      "scriptId":"u25"},
    "6d2f1dda730a4fa580ba908aa1f88356":{
      "scriptId":"u26"},
    "7b8554d3710642f8a818cd0d62a1d8ea":{
      "scriptId":"u27"},
    "ea12359fcd474209bb16bac0cb99ef8c":{
      "scriptId":"u28"},
    "4a2cbd9936804e6bab39ec558fcb5c89":{
      "scriptId":"u29"},
    "24d39249329f42d89afd93c2b841c4dd":{
      "scriptId":"u30"}}});