$axure.loadCurrentPage({
  "url":"标签选择页面.html",
  "generationDate":new Date(1417659391771.18),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6f9e06b7cbb9492cade2624707438612",
    "type":"Axure:Page",
    "name":"标签选择页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e932359b93104bcbb33875ec4bb380db",
          "label":"背景",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":399,
              "height":745}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1e4e2ba941646b5a83574f85dd76476",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":399,
                  "height":745}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/中国大学生在线/背景_u0.png"}},
{
          "id":"aa3c1d1cbb0b4921bbb02af6bee0a35c",
          "label":"头部",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFEB1015},
            "location":{
              "x":35,
              "y":138},
            "size":{
              "width":319,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06ded7d279794288880004febada506d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEB1015},
                "location":{
                  "x":35,
                  "y":138},
                "size":{
                  "width":319,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页--未登录/头部_u2.png"}},
{
          "id":"ab770a0b8d3b4439b042fb3760432b2f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":193},
            "size":{
              "width":317,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页--未登录/u4_line.png"}},
{
          "id":"f47b66e63d93491796084d83a94971fb",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":362},
            "size":{
              "width":317,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页--未登录/u4_line.png"}},
{
          "id":"6dfd1a500b8a48f0afe772ac8ecee2a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":38,
              "y":142},
            "size":{
              "width":13,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c463afc9ea86471ca6f04390b8141014",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":38,
                  "y":142},
                "size":{
                  "width":13,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页--未登录",
                      "target":{
                        "targetType":"page",
                        "url":"首页--未登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"33af71993f2f4424b0cbfcc23432704d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "location":{
              "x":50,
              "y":173},
            "size":{
              "width":53,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3a0a57384784027b25ebea1e5bfe259",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "location":{
                  "x":50,
                  "y":173},
                "size":{
                  "width":53,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4cf6119afcc14db0bde8de0444ff1344",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":120,
              "y":179},
            "size":{
              "width":124,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43885c1e20324bcd949e4d8f5d7cea13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":120,
                  "y":179},
                "size":{
                  "width":124,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"387fe3fbe7344419a98add031c693e06",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":60,
              "y":213},
            "size":{
              "width":43,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06ecc30b376e40e1a5ff6cd13c905a2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":60,
                  "y":213},
                "size":{
                  "width":43,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/标签选择页面/u12.png"}},
{
          "id":"6aeed4766ab148048cddfb0840652578",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":126,
              "y":213},
            "size":{
              "width":43,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"985fa912e83143658374871e9128eda1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":126,
                  "y":213},
                "size":{
                  "width":43,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/标签选择页面/u14.png"}},
{
          "id":"fcbd12285d824ee48684ce3890678e64",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":191,
              "y":213},
            "size":{
              "width":43,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb6d0c9ab5a84f68bcf88e56c224d47c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":191,
                  "y":213},
                "size":{
                  "width":43,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/标签选择页面/u14.png"}},
{
          "id":"26f2a049ec7f4086ab4116c3b44f6a19",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":257,
              "y":213},
            "size":{
              "width":43,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1db570365674acf992edb39c9fb8f7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":257,
                  "y":213},
                "size":{
                  "width":43,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/标签选择页面/u14.png"}},
{
          "id":"454b233a121c47afb996e46eca9e9b56",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":60,
              "y":260},
            "size":{
              "width":43,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"304067273f7b4878ac84ff706efaf256",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":60,
                  "y":260},
                "size":{
                  "width":43,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/标签选择页面/u14.png"}},
{
          "id":"9286d5e10e8149fa8019894ad68f5f13",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":126,
              "y":260},
            "size":{
              "width":43,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d4ae08dd241496ba01accfa0bfe9241",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":126,
                  "y":260},
                "size":{
                  "width":43,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/标签选择页面/u14.png"}},
{
          "id":"bca0393bbec241118cadc2b3d578c752",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "location":{
              "x":50,
              "y":372},
            "size":{
              "width":53,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5ee20736bb4428c82dc8fe884325752",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "location":{
                  "x":50,
                  "y":372},
                "size":{
                  "width":53,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c74fe1ea655b47a28e8219e621351641",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":60,
              "y":401},
            "size":{
              "width":43,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df6d916a10144da184e6a6089a16fea1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":60,
                  "y":401},
                "size":{
                  "width":43,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/标签选择页面/u14.png"}},
{
          "id":"d812c3e797a64252b1580c372321dfe4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":126,
              "y":401},
            "size":{
              "width":43,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd42c4b1499c4d85bb10bfde791b9829",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":126,
                  "y":401},
                "size":{
                  "width":43,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/标签选择页面/u14.png"}},
{
          "id":"81f3480043e94d51a420e472c9084b0b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":191,
              "y":401},
            "size":{
              "width":43,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77fc9b28dab2492fa62e2a80044e8983",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":191,
                  "y":401},
                "size":{
                  "width":43,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/标签选择页面/u14.png"}},
{
          "id":"d8468ba034b54ceaa5b2a8686a798b46",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":257,
              "y":401},
            "size":{
              "width":43,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3eb3bd31de794a8b868bcce06a486fed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":257,
                  "y":401},
                "size":{
                  "width":43,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/标签选择页面/u14.png"}},
{
          "id":"109daeaa7356495fa54f5ec3de8e5790",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":60,
              "y":449},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c18e3e5370d445c95ed3cfbfdec4c22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":60,
                  "y":449},
                "size":{
                  "width":60,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/标签选择页面/u34.png"}},
{
          "id":"34d4a2b54049420cb491207205a846e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":140,
              "y":449},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f271045fe2dd41978bbc4e61127bdb8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":140,
                  "y":449},
                "size":{
                  "width":60,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/标签选择页面/u34.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "e932359b93104bcbb33875ec4bb380db":{
      "scriptId":"u0"},
    "e1e4e2ba941646b5a83574f85dd76476":{
      "scriptId":"u1"},
    "aa3c1d1cbb0b4921bbb02af6bee0a35c":{
      "scriptId":"u2"},
    "06ded7d279794288880004febada506d":{
      "scriptId":"u3"},
    "ab770a0b8d3b4439b042fb3760432b2f":{
      "scriptId":"u4"},
    "f47b66e63d93491796084d83a94971fb":{
      "scriptId":"u5"},
    "6dfd1a500b8a48f0afe772ac8ecee2a6":{
      "scriptId":"u6"},
    "c463afc9ea86471ca6f04390b8141014":{
      "scriptId":"u7"},
    "33af71993f2f4424b0cbfcc23432704d":{
      "scriptId":"u8"},
    "d3a0a57384784027b25ebea1e5bfe259":{
      "scriptId":"u9"},
    "4cf6119afcc14db0bde8de0444ff1344":{
      "scriptId":"u10"},
    "43885c1e20324bcd949e4d8f5d7cea13":{
      "scriptId":"u11"},
    "387fe3fbe7344419a98add031c693e06":{
      "scriptId":"u12"},
    "06ecc30b376e40e1a5ff6cd13c905a2a":{
      "scriptId":"u13"},
    "6aeed4766ab148048cddfb0840652578":{
      "scriptId":"u14"},
    "985fa912e83143658374871e9128eda1":{
      "scriptId":"u15"},
    "fcbd12285d824ee48684ce3890678e64":{
      "scriptId":"u16"},
    "bb6d0c9ab5a84f68bcf88e56c224d47c":{
      "scriptId":"u17"},
    "26f2a049ec7f4086ab4116c3b44f6a19":{
      "scriptId":"u18"},
    "d1db570365674acf992edb39c9fb8f7f":{
      "scriptId":"u19"},
    "454b233a121c47afb996e46eca9e9b56":{
      "scriptId":"u20"},
    "304067273f7b4878ac84ff706efaf256":{
      "scriptId":"u21"},
    "9286d5e10e8149fa8019894ad68f5f13":{
      "scriptId":"u22"},
    "1d4ae08dd241496ba01accfa0bfe9241":{
      "scriptId":"u23"},
    "bca0393bbec241118cadc2b3d578c752":{
      "scriptId":"u24"},
    "f5ee20736bb4428c82dc8fe884325752":{
      "scriptId":"u25"},
    "c74fe1ea655b47a28e8219e621351641":{
      "scriptId":"u26"},
    "df6d916a10144da184e6a6089a16fea1":{
      "scriptId":"u27"},
    "d812c3e797a64252b1580c372321dfe4":{
      "scriptId":"u28"},
    "fd42c4b1499c4d85bb10bfde791b9829":{
      "scriptId":"u29"},
    "81f3480043e94d51a420e472c9084b0b":{
      "scriptId":"u30"},
    "77fc9b28dab2492fa62e2a80044e8983":{
      "scriptId":"u31"},
    "d8468ba034b54ceaa5b2a8686a798b46":{
      "scriptId":"u32"},
    "3eb3bd31de794a8b868bcce06a486fed":{
      "scriptId":"u33"},
    "109daeaa7356495fa54f5ec3de8e5790":{
      "scriptId":"u34"},
    "1c18e3e5370d445c95ed3cfbfdec4c22":{
      "scriptId":"u35"},
    "34d4a2b54049420cb491207205a846e0":{
      "scriptId":"u36"},
    "f271045fe2dd41978bbc4e61127bdb8e":{
      "scriptId":"u37"}}});